### ISSUE TITLE
Forecaster Autoreg converting data_train to index frequency=1 instead of index frequency=D

### ISSUE THREAD

**Issue by tn2094** [JoaquinAmatRodrigo/skforecast#147]
Hello, 

I m using the current df (https://www.kaggle.com/datasets/aramacus/electricity-demand-in-victoria-australia) and when I tried to implement the code used here (https://www.cienciadedatos.net/documentos/py29-forecasting-electricity-power-demand-python.html)  I have the following issue : 

when I run this code 
forecaster = ForecasterAutoreg(
                  regressor = make_pipeline(StandardScaler(), Ridge(random_state=123)),
                    lags      = 20
                    )

forecaster.fit(y=data_train.price)
 print(forecaster)

The data is at day granularity so i also did
data = data.asfreq('1D')

as you can see below my training frequency/range are not detecting the timestamp format while my format is correct when i run 
print(type(data_train.index())

What I am doing wrong? 
![image](https://user-images.githubusercontent.com/73368150/164693668-7a00ed45-b7ca-4571-8acc-f0d65f0be301.png)

![type df](https://user-images.githubusercontent.com/73368150/164692224-16ad9d17-3305-4da7-baa9-0897c212e2d6.png)

Many thanks for your input !

**Comment by JavierEscobarOrtiz** [comment]
Hello @tn2094,

I downloaded your dataset and use the following code and it works for me:

``` python
url = (r'/home/javi/Downloads/complete_dataset.csv')
data = pd.read_csv(url, sep=',', header=0)

data['date'] = pd.to_datetime(data['date'], format='%Y-%m-%d')
data = data.set_index('date')
data = data.asfreq('1D')
data = data.sort_index()
data.info()
``` 
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2106 entries, 2015-01-01 to 2020-10-06
Freq: D
Data columns (total 13 columns):
...
``` python
# Split data into train-val-test
end_train = '2019-12-31 23:59:00'
end_validation = '2020-06-30 23:59:00'
data_train = data.loc[: end_train, :].copy()
data_val   = data.loc[end_train:end_validation, :].copy()
data_test  = data.loc[end_validation:, :].copy()

print(f"Train dates      : {data_train.index.min()} --- {data_train.index.max()}")
print(f"Validation dates : {data_val.index.min()} --- {data_val.index.max()}")
print(f"Test dates       : {data_test.index.min()} --- {data_test.index.max()}")
``` 
Train dates         : 2015-01-01 00:00:00 --- 2019-12-31 00:00:00
Validation dates : 2020-01-01 00:00:00 --- 2020-06-30 00:00:00
Test dates          : 2020-07-01 00:00:00 --- 2020-10-06 00:00:00
``` python
forecaster = ForecasterAutoreg(
                    regressor = make_pipeline(StandardScaler(), Ridge(random_state=123)),
                    lags = 20
                    )

forecaster.fit(y=data_train['RRP'])
forecaster
``` 
ForecasterAutoreg 
Regressor: Pipeline(steps=[('standardscaler', StandardScaler()),
                ('ridge', Ridge(random_state=123))]) 
Lags: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 
Window size: 20 
Included exogenous: False 
Type of exogenous variable: None 
Exogenous variables names: None 
Training range: [Timestamp('2015-01-01 00:00:00'), Timestamp('2019-12-31 00:00:00')] 
Training index type: DatetimeIndex 
Training index frequency: D 
Regressor parameters: {'standardscaler__copy': True, 'standardscaler__with_mean': True, 'standardscaler__with_std': True, 'ridge__alpha': 1.0, 'ridge__copy_X': True, 'ridge__fit_intercept': True, 'ridge__max_iter': None, 'ridge__normalize': 'deprecated', 'ridge__positive': False, 'ridge__random_state': 123, 'ridge__solver': 'auto', 'ridge__tol': 0.001} 
Creation date: 2022-04-23 10:14:51 
Last fit date: 2022-04-23 10:14:51 
Skforecast version: 0.4.3 

Maybe you are setting the frequency (as you said `data = data.asfreq('1D')`) after the split data to data_train so data_train hasn't a freq?

Hope you can solve your problem with this code!

**Comment by tn2094** [comment]
Great ! Many thanks it works now
