### ISSUE TITLE
ForecasterAutoreg: include lags of exog in skforecast.model_selection.grid_search_forecaster ?

### ISSUE THREAD

**Issue by zora-no** [JoaquinAmatRodrigo/skforecast#153]
The docs say: "ForecasterAutoreg and ForecasterAutoregCustom allow to include exogenous variables as predictors as long as their future values are known, since they must be included during the predict process." [source](https://joaquinamatrodrigo.github.io/skforecast/0.1/guides/autoregresive-forecaster-exogenous.html)
However, according to the image on the linked website, only the future value of the exogenous variable is included as a predictor, and not its lags. **Is there a way to also include the lags of the exogenous variables, not just of the target, in skforecast?**
I'm aware that this is possible with a fixed number of lags by using ForecasterAutoregCustom(), but I'm wondering if there is a way to incorporate it into skforecast.model_selection.grid_search_forecaster (in order to not use a fixed number of lags)?
Thanks a lot!

**Comment by zora-no** [comment]
Also, to clarify: If I want to predict index=10, is the value of the exogenous variable that is included from index=10 or index=9?

**Comment by JoaquinAmatRodrigo** [comment]
Hi @zora-no 
Right now, there is no option to create lags of exog variables automatically. However,  you could manually convert the exog variable in to a data frame, where each column is a different lag of the exog. Then, using a regressors that allows for feature selection such as ridge, lasso, gradient-boosting in order to identify the more informative lags.

I hope this helps. We will consider implementing this feature in future releases.

**Comment by zora-no** [comment]
Hi @JoaquinAmatRodrigo, thanks for your response!
1. If I create this df, where/ how can I pass it (since it would still be separate from the "normal" Xtrain matrix)?
2. Is there also no way to do manually include other variables using the custom forecaster? Or to somehow access/manipulate the Xtrain matrix of the forecaster directly?

**Comment by JavierEscobarOrtiz** [comment]
Hello @zora-no,

> 1. If I create this df, where/ how can I pass it (since it would still be separate from the "normal" Xtrain matrix)?

To add exogenous variable to the train matrix you should declare them inside the `fit()`method, for example:

``` python

# Create and fit forecaster
# ==============================================================================
forecaster = ForecasterAutoreg(
                    regressor = RandomForestRegressor(random_state=123),
                    lags      = 15
            )

forecaster.fit(
    y    = data_train['y'],
    exog = data_train[['exog_1_lag1', 'exog_1_lag2', 'exog2_lag0', 'exog_3_lag5']]
)
```

*Note: `data_train` is a dataframe with the serie, `y`, and the exogenous variables (one for each lag, you can use `pandas.DataFrame.shift()` method to create the lags: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shift.html)*

You can find a good explanation about exogenous variables in **skforecast** here:

https://joaquinamatrodrigo.github.io/skforecast/latest/notebooks/autoregresive-forecaster-exogenous.html

> 2. Is there also no way to do manually include other variables using the custom forecaster? Or to somehow access/manipulate the Xtrain matrix of the forecaster directly?

Imagine the next example:

``` python

# Custom function to create predictors
# ==============================================================================
def create_predictors(y):
    '''
    Create first 10 lags of a time series.
    Calculate moving average with window 20.
    '''

    lags = y[-1:-11:-1]
    mean = np.mean(y[-20:])
    predictors = np.hstack([lags, mean])

    return predictors

# Create forecaster
# ==============================================================================
forecaster = ForecasterAutoregCustom(
                    regressor      = RandomForestRegressor(random_state=123),
                    fun_predictors = create_predictors,
                    window_size    = 20
             )
```

The function `create_predictors(y)` only can have as an argument the series `y`, to transform the exogenous variables you should do it outside the forecaster and pass them as the previous example in the `fit()` method.

More info:

https://joaquinamatrodrigo.github.io/skforecast/latest/notebooks/custom-predictors.html

**Comment by tkaraouzene** [comment]
Hi ! 
First of all thanks for this nice library.
Just to say that I would also be interested by this feature.

It would be nice to consider lags for exogenous variable bu not only for ``grid_search_forecaster`` but also for ``ForecasterAutoreg``

I've implemented a sloution to compute lags for exogenous data before the fit.
One of the issue is that these lags are not stored in the ``last_window`` so it force to overwritte it.

Thanks again

**Comment by tkaraouzene** [comment]
Hi !

To complete my previous post,
If exog_lags are computed, they also have to be stored for the predict.

bellow a suggestion:

**[original code]:**

```python
def fit(...):
    ...
    # The last time window of training data is stored so that lags needed as
    # predictors in the first iteration of `predict()` can be calculated.
    self.last_window = y_train.iloc[-self.max_lag:].copy()
```

**[modified code]:**

```python
def fit(...):
    ...
    # The last time window of training data is stored so that lags needed as
    # predictors in the first iteration of `predict()` can be calculated.
    self.y_last_window = y_train.iloc[-self.max_lag:].copy()
    self.exog_last_window = X_train.iloc[-self.max_lag:].copy()
```
