### ISSUE TITLE
BibTex Citation

### ISSUE THREAD

**Issue by CalenDario13** [JoaquinAmatRodrigo/skforecast#160]
Hi there, I suggest you to write a short paper and try to publish it, so it is possible to cite your work into other papers throughout google scholar.
I am writing a thesis, is it possible to cite you in any way? 
Thank you

**Comment by CalenDario13** [comment]
You can also do in an easier way, like this:

https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository

**Comment by JoaquinAmatRodrigo** [comment]
Hi @CalenDario13 
Thanks a lot for the suggestion. For now we are following the option offered by github. Be aware that the last released version of skforecast is 0.4.3

APA format:

Amat Rodrigo, J., & Escobar Ortiz, J. (2022). skforecast (Version 0.4.3) [Computer software]

BibTeX format:

@software{Amat_Rodrigo_skforecast_2022,
author = {Amat Rodrigo, Joaquin and Escobar Ortiz, Javier},
license = {MIT},
month = {3},
title = {{skforecast}},
version = {0.4.3},
year = {2022}
}
