### ISSUE TITLE
Problems between versions of statsmodels and scipy

### ISSUE THREAD

**Issue by andresliszt** [JoaquinAmatRodrigo/skforecast#163]
There is a dependency problem with ```scikit-learn>=1.0``` and ```statsmodels>=0.12, <=0.13```, because of  scipy's dependency on sckit-learn .Versions of scipy after 1.8.0 have problems with the versions of statsmodels I mentioned as described [here](https://stackoverflow.com/questions/71106940/cannot-import-name-centered-from-scipy-signal-signaltools).  I got the same problem as the stackoverflow post when I tried to import  ```statsmodels.tsa.api.ExponentialSmoothing``` on my virtual environment after installed ```skforecast```.

```
from statsmodels.tsa.api import ExponentialSmoothing

>>> ImportError: cannot import name '_centered' from 'scipy.signal.signaltools' (C:\ExamplePath\.venv\lib\site-packages\scipy\signal\signaltools.py)

```

I ran this on Windows using ```python 3.9.7```

**Comment by JavierEscobarOrtiz** [comment]
Hi @andresliszt,

Thanks for letting us know. We will check if statsmodels==0.13.2 have no issues with skforecast and update the requirements as the error you mention is fixed in statsmodels==0.13.2.

Thank you.
