### ISSUE TITLE
Pipelines with Column Transformer with Mixed Types fails

### ISSUE THREAD

**Issue by andresliszt** [JoaquinAmatRodrigo/skforecast#166]
Hello! :) Nice work thank you!. The method ``ForecasterAutoreg.create_train_X_y`` builds the matrix ``X`` to feed the regressor calling ``ForecasterAutoreg.regressor.fit`` and ``X`` is always a pandas DataFrame (except if the regressor is a xgboost). Later, when the ``ForecasterAutoreg.regressor.predict`` method is called in a recursive form, each row is a numpy array of shape ``(1, number_lags + number_exog)``. This can lead to errors in pipelines that use column transformers because sometimes you need to have the names of the columns to know who to apply the transformations to.

Here is a reproducible example

```python
    import numpy as np
    import pandas as pd
    from sklearn.compose import ColumnTransformer
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
    from skforecast.ForecasterAutoreg import ForecasterAutoreg

    lags = 5

    data = pd.Series(
        np.random.rand(100),
        index=pd.date_range("2019-01-01", freq="D", periods=100),
    )
    exog = pd.DataFrame(
        {
            "exog_1": np.random.choice(["A", "B", "C"], len(data)),
            "exog_2": np.random.choice(["D", "E", "F"], len(data)),
        },
        index=data.index,
    )

    preprocessor = ColumnTransformer(
        transformers=[
            (
                "predictors",
                MinMaxScaler(),
                [f"lag_{i}" for i in range(1, lags+ 1)],
            ),
            ("categorical", OneHotEncoder(), ["exog_1", "exog_2"]),
        ],
    )

    pipeline = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("regressor", DecisionTreeRegressor()),
        ],
    )

    forecaster = ForecasterAutoreg(
        lags=lags,
        regressor=pipeline,
    )
    # No problem with fit, every works fine!
    forecaster.fit(data, exog = exog)
    # Here is the problem :(
    forecaster.predict(steps = 1, exog = exog)

 File "~\.venv\lib\site-packages\sklearn\utils\__init__.py", line 353, in _safe_indexing
    raise ValueError(
ValueError: Specifying the columns using strings is only supported for pandas DataFrames

```
The error occurs as I said, because ``predict`` is expecting a pandas DataFrame. A StackOverflow post is [here](https://stackoverflow.com/questions/54298550/attributeerror-when-using-columntransformer-into-a-pipeline) and the example of Column transformer with mixed dtypes is [here](https://scikit-learn.org/stable/auto_examples/compose/plot_column_transformer_mixed_types.html).

**EDIT**

Passing the column index instead of its name, works

```python
  preprocessor = ColumnTransformer(
      transformers=[
          (
              "predictors",
              MinMaxScaler(),
              [0,1,2,3,4],
          ),
          ("categorical", OneHotEncoder(), [5,6]),
      ],
  )

  pipeline = Pipeline(
      steps=[
          ("preprocessor", preprocessor),
          ("classifier", DecisionTreeRegressor()),
      ],
  )

```

I think it would be a good idea to document and/or protect the error inside the code

**Comment by JoaquinAmatRodrigo** [comment]
Hi @andresliszt,
You are right, the current version of skforecast (0.4.3) does not allow including ColumnTransformer in the pipeline used as regressor, so if the preprocessing transformations only apply to some specific columns, they have to be applied on the data set before training the model. We are working on solving this, since ColumnTransformers are key players. We expect to include it in the next release.

**Comment by JoaquinAmatRodrigo** [comment]
I just saw you find a solution. We will include it in the docs as soon as possible. thanks for figuring this out @andresliszt!

**Comment by JoaquinAmatRodrigo** [comment]
Feature added in version 0.5.0

https://joaquinamatrodrigo.github.io/skforecast/0.5.0/user_guides/sklearn-transformers-and-pipeline.html
