### ISSUE TITLE
Predicciones del futuro

### ISSUE THREAD

**Issue by roquelealfr** [JoaquinAmatRodrigo/skforecast#168]
Hola, muy bueno tu tutorial de la demanda electrica https://www.cienciadedatos.net/documentos/py29-forecasting-demanda-energia-electrica-python.html
Me gustaria saber cual es la siguiente parte del codigo para ponerlo en produccion, es decir aqui haces las estimaciones hasta la ultima fecha del test 31 diciembre 2014, pero si yo quiero saber la demanda para enero 2015 es decir el futuro, que se deberia hacer.
Pienso que con eso estaria completo el tutorial, gracias por leerle, saludos

**Comment by JoaquinAmatRodrigo** [comment]
Hola @roquelealfr,
La predicción de valores futuros con un forecaster ya entrenado se consigue con el método `predict()` . Es importante tener en cuenta que, si el forecaster utiliza variables exógenas, estas tienen que ser aportadas. Pongo a continuación un par de links a la documentación que te pueden resultar útiles.

https://joaquinamatrodrigo.github.io/skforecast/0.4.3/notebooks/autoregresive-forecaster.html

https://joaquinamatrodrigo.github.io/skforecast/0.4.3/notebooks/forecaster-in-production.html
