### ISSUE TITLE
Conduct prediction interval for ForecasterAutoregMultiOutput

### ISSUE THREAD

**Issue by kennis222** [JoaquinAmatRodrigo/skforecast#175]
Hi developer,

Since ForecasterAutoregMultiOutput does not contain any API for conducting prediction interval, I try to extract the forecast.regressor and try by myself. However, I realize that if I directly use the regressor to fit(X_train,y_train) and predict(X_train), the result just outputs the condition of fitting without considering the prediction step (for example set step = 6). Because I would like to use the training model residuals to conduct the prediction interval, now the APIs of ForecasterAutoregMultiOutput cannot satisfy my need. 

Would you like to provide any suggestion for me to conduct the prediction interval, either in bootstrapping or based on training residuals?

Thank you

**Comment by JavierEscobarOrtiz** [comment]
Hello @kennis222,

You can find a good example on how to perform interval prediction in a `ForecasterAutoregMultiOutput` using quantile regression in those documents: 

https://joaquinamatrodrigo.github.io/skforecast/latest/notebooks/prediction-intervals.html#quantile-regression-models (see "quantile regression models" section)

https://www.cienciadedatos.net/documentos/py42-forecasting-prediction-intervals-machine-learning.html

Hope it helps!
