### ISSUE TITLE
Typos in "Recursive multi-step forecasting with exogenous variables" documentation

### ISSUE THREAD

**Issue by kaionwong** [JoaquinAmatRodrigo/skforecast#199]
I have found a bug in the python code on this [page](https://joaquinamatrodrigo.github.io/skforecast/0.3/guides/autoregresive-forecaster-exogenous.html) "Recursive multi-step forecasting with exogenous variables". 

If `exog = data_train[['exog_1', 'exog_2']].values` is run directly, it will give this error `Exception: "exog" must be "pd.Series" or "pd.DataFrame".` 

Correction, this should be `exog = data_train[['exog_1', 'exog_2']]` without the `.values` since a pandas `pd.DataFrame` is expected. Please make the correction in the appropriate documentation page and code examples, thanks.

**Comment by JavierEscobarOrtiz** [comment]
Hello @kaionwong,

The page you refer to is the documentation for an older version of skforecast, specifically **0.3.0** where the code was different.

This is the same page but for version **0.4.3**: [Recursive multi-step forecasting with exogenous variables](https://joaquinamatrodrigo.github.io/skforecast/0.4.3/notebooks/autoregresive-forecaster-exogenous.html).

Please note that you can change the version referenced in the documentation with this selector:

![imagen](https://user-images.githubusercontent.com/95030312/180953742-3e618708-4995-4c96-8deb-7452b881d6ce.png)

Hope it helps!
