### ISSUE TITLE
Question regarding Documentation: In Production

### ISSUE THREAD

**Issue by nkotwal93** [JoaquinAmatRodrigo/skforecast#206]
https://joaquinamatrodrigo.github.io/skforecast/0.4.3/notebooks/forecaster-in-production.html 

The note at the end of this page states the following:
**It is important to note that `last_window`'s length must be enough to include the maximum lag used by the forecaster. For example, if the forecaster uses lags 1, 24, 48, `last_window` must include the last 72 values of the series.**

I do not understand why would you need 72 values in the above example when your MaxLag is 48?

**Comment by JavierEscobarOrtiz** [comment]
Hello @nkotwal93,

Thanks for the note. Correct, `last_window`'s length should be the same as the **maximum lag**. In this case, the correct would be _"if the forecaster uses lags 1, 24, 48 `last_window` must include the last **48 values** of the series"_. 

We will correct it! Thank you 😄

**Comment by JoaquinAmatRodrigo** [comment]
Fixed it in version 0.5.0.
