### ISSUE TITLE
Direct multi-step forecasting Single Prediction

### ISSUE THREAD

**Issue by CalenDario13** [JoaquinAmatRodrigo/skforecast#230]
It may be useful to five the possibility to decide whether to predict all the models, or just the last one, because sometimes it is required only the last prediction and not all the past ones.

**Comment by JoaquinAmatRodrigo** [comment]
Hi @CalenDario13,
Thanks for the suggestion. This feature makes sence and it will only involve adding an additional argument.
We add it to the list of features of future releases.

Thanks!

**Comment by JavierEscobarOrtiz** [comment]
Hello, 

We added this feature in skforecast 0.6.0.

https://joaquinamatrodrigo.github.io/skforecast/latest/user_guides/direct-multi-step-forecasting.html#prediction

Hope it helps!
