### ISSUE TITLE
Question: Estrategia de validación cruzada demasiado costosa

### ISSUE THREAD

**Issue by benitocm** [JoaquinAmatRodrigo/skforecast#246]
Hola,

Creo que estás haciendo un gran trabajo con skforecast y los tutoriales que lo acompañan son muy didácticos.
Antes de empezar a usar skforecast la validación cruzada que hago, usando por ejemplo LightGBM, es basarme en [TimeSeriesSplit](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html) para crear, por ejemplo, 5 particiones, de manera que el proceso de validación cruzada queda más o menos así (la primera columna indica la parte de entrenamiento y la segunda la de validación):
[0,1,2,3,4]                  [5]
[0,1,2,3,4,5]               [6]
[0,1,2,3,4,5,6]            [7]
[0,1,2,3,4,5,6,7]         [8]
[0,1,2,3,4,5,6,7,8]      [9]

En el ejemplo de arriba tendría 5 conjuntos de predicciones validadas y la métrica final sería por ejemplo la media de las métricas obtenidas en cada una de las validaciones. Por tanto, cualquier prueba de selección de modelo estaría sujeta a este bucle de validación cruzada. Al tener 5 particiones o "folds", el modelo habría sido re-entrenado 5 veces lo cual permite usar este bucle de validación cruzada a la hora, por ejemplo, de ajustar hiperparámetros.

Al usar la libreria skforecast, veo que se crea un "fold (para el caso del ForecasterAutoregDirect) del tamaño del número de pasos. En mi caso, esto hace casi siempre inviable el uso de la opción "refit=True", ya que el número de "folds" es muy alto  y por tanto se hacen muchos "re-entrenamientos".ç

Por favor, ¿podrías indicarme si hay alguna manera de usar la opción "refit=True" si que haya tantos "re-entrenamientos"?

Un saludo y muchas gracias

**Comment by JavierEscobarOrtiz** [comment]
Buenas @benitocm,

La validación de `TimeSeriesSplit` está implementada en skforecast con la función `backtesting_forecaster` dentro del módulo `model_selection`. ([Documentación Backtesting](https://joaquinamatrodrigo.github.io/skforecast/lastest/user_guides/backtesting.html))

Hay algunos parámetros que te pueden ayudar a reducir el tiempo de ejecución:

```python
metric, predictions_backtest = backtesting_forecaster(
                                   forecaster         = forecaster,
                                   y                  = data['y'],
                                   initial_train_size = len(data.loc[:end_train]),
                                   fixed_train_size   = False,
                                   steps              = 10,
                                   metric             = 'mean_squared_error',
                                   refit              = True,
                                   verbose            = True
                               )
```

- Los argumentos `refit`, `fixed_train_size` te permiten seleccionar si se reentrena tu modelo o no y cómo lo hace. Te recomiendo mirar los gifs en la [documentación](https://joaquinamatrodrigo.github.io/skforecast/lastest/user_guides/backtesting.html) para entenderlo. La opción más rápida es `refit = False` (el modelo solo se entrena al inicio).
- `initial_train_size` y `steps` te permiten configurar el tamaño del set de entrenamiento inicial y de las predicciones. Esto conlleva aumentar o disminuir el número y tamaño de los folds.

La validación de Backtesting se emplea también al [optimizar los hiperparámetros](https://joaquinamatrodrigo.github.io/skforecast/latest/user_guides/hyperparameter-tuning-and-lags-selection.html).

Espero que te ayude!

**Comment by benitocm** [comment]
Hola,

Muchísimas gracias por la respuesta.

La documentación la he mirado bastantes veces, aunque lo mismo no he  malinterpretado el parámetro  `steps`. En mi caso, tengo 10.000 muestras para entrenamiento, 2.000 para validación y 1000 para test.  Estoy utilizando  `ForecasterAutoregDirect` para hacer realizar predicciones de 8 pasos. Actualmente, el parámetro `steps` en el método `backtesting_forecaster` lo establezco a 8 con lo que se crean aproximadamente 2000/8 = 250 "folds" y, por tanto, el modelo se re-entrena 250 veces en el caso de que `refit=True`.  ¿Estoy usándolo incorrectamente?, ¿tendría que cambiar el parámetro `steps` para que tener menos "folds"?.

Un saludo y de nuevo muchas gracias.

**Comment by JavierEscobarOrtiz** [comment]
Buenas!

Es importante tener en cuenta que [ForecasterAutoregDirect](https://joaquinamatrodrigo.github.io/skforecast/latest/user_guides/direct-multi-step-forecasting.html) entrena un modelo diferente para cada step. 

Por ejemplo, al declarar el forecaster como muestro a continuación el objecto `forecaster` almacena 36 regresores `Ridge`, uno para cada step.

```python
forecaster = ForecasterAutoregDirect(
                 regressor = Ridge(),
                 steps     = 36,
                 lags      = 15
             )
```
Después, al usar el método `predict()` decides qué steps predecir, del 1 a 36 como máximo. Si por ejemplo señalas `steps = 6` realizarás la predicción de los siguientes 6 pasos usando solo los primeros 6 modelos (los 30 siguientes se han entrenado aunque no se usen).

Respecto a tu `backtesting_forecaster`, si al declarar el `ForecasterAutoregDirect` has usado también `steps = 8`, significa que en cada reentrenamiento estás entrenado 8 modelos. Por tanto, el número real de reentrenamientos es de 250*8 = 2000 veces.

Te recomendaría, si quieres mantener el mismo número de `steps`, reducir el número de observaciones o utilizar un `ForecasterAutoreg`, este utiliza un único modelo para todas las predicciones.

Saludos.

**Comment by benitocm** [comment]
Hola otra vez! 

Gracias por la respuesta. Si soy conciente de que al tener 8 steps estoy entrenando 8 modelos (de manera similar que usar [MultiOutputRegressor](sklearn.multioutput](https://scikit-learn.org/stable/modules/classes.html#modulesklearn.multioutput.MultiOutputRegressor)
