### ISSUE TITLE
Support for python 3.10

### ISSUE THREAD

**Issue by chriss1245** [JoaquinAmatRodrigo/skforecast#252]
Hi, 

I am not able to install skforecast in python 3.10 . It seems that  statsmodels dependency (>=0.12, <=0.13) does not have a wheel for python  3.10

**Comment by JoaquinAmatRodrigo** [comment]
Hi @chriss1245 
Why OS are you using? 

I have try on linux (Linux-5.15.0-48-generic-x86_64-with-glibc2.31) and it works fine:

`conda create -n py310  python=3.10`
`pip install skforecast`

**Comment by chriss1245** [comment]
Thanks for the quick reply. I tried to install it on another environment and I it worked well.
I do not know why it did not work before. Just in case: I am using fedora workstation 36.
