### ISSUE TITLE
Direct-Recursive Hybrid Strategies

### ISSUE THREAD

**Issue by kennis222** [JoaquinAmatRodrigo/skforecast#253]
Hello developers,

Would like to consider develop Direct-Recursive hybrid strategies?

**Comment by JoaquinAmatRodrigo** [comment]
Hi @kennis222,

The Direct-Recursive hybrid strategy is not in our scope right now. We will test first the potential benefits of model stacking.

**Comment by kennis222** [comment]
Cool, thanks. Look forward the model stacking.
