### ISSUE TITLE
Backtesting with overlap in the validation sets [parameter defining forecast origin shift]

### ISSUE THREAD

**Issue by flaviojfpereira** [JoaquinAmatRodrigo/skforecast#275]
Hi guys.
I was thinking about performing backtesting with overlap in the validation sets. That could be done by having a parameter to define how many periods the forecast origin should advance/shift.

I'll leave an image below that shows the desired backtesting method.

What do you guys think?

![Screenshot 2022-10-27 at 12 12 26](https://user-images.githubusercontent.com/32712708/198272744-a2446bd3-c65e-4335-99b2-5537b9ec0f79.png)

**Comment by JoaquinAmatRodrigo** [comment]
Hi @flaviojfpereira,

The problem I see with the overlapping approach is that will end up having multiple predictions for the same point in time. Which one should be reported?

**Comment by esmeriz** [comment]
Hello all,

@JoaquinAmatRodrigo Yes you end up but each prediction has a different meaning. I would suggest returning all of them. For example: I want to perform a weekly forecast over the following 4 weeks. This is a case of a forecast being performed with an horizon of 4 weeks and with a step of 1 week. If I have an array of N x 4 (N predictions for each of the 4 weeks ahead) I would be able to analyse the accuracy of my predictions for different time horizons.

**Comment by JoaquinAmatRodrigo** [comment]
Hi all,

Currently, all backtesting methods must return a single prediction per point in time to be compatible with the other functionalities of the API. Nevertheless, we add it to the list of next features and we will try to fit it into future releases.
Thanks a lot for the suggestion!

**Comment by JoaquinAmatRodrigo** [comment]
Hi, 
It has been more than 60 days since the last activity on this GitHub issue. Since we have not received any updates or progress reports, we will be closing this issue.

If this issue is still relevant and requires attention, please feel free to reopen it and provide an update. We appreciate your contributions and would love to see this issue resolved if it is still relevant.

Thank you for your participation and cooperation!
