### ISSUE TITLE
Pip Installation Fails on Macbook Pro M1

### ISSUE THREAD

**Issue by bernhard-kaindl** [JoaquinAmatRodrigo/skforecast#280]
When trying to install skforecast using `pip install skforecast`, the install process fails with the following output:

```
      
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
```
Unfortunately, the full output is too large, however this seems to happen when trying to install the build dependencies for `statsmodels`.

Setup:
MacBook Pro M1
MacOS Monterey 12.6

Python 3.9.13 (main, Oct  5 2022, 11:08:35) 
Clang 14.0.0 (clang-1400.0.29.102)

**Comment by JavierEscobarOrtiz** [comment]
Hello @bernhard-kaindl 

Please, could you try to install it with python 3.9.4 or lower?

I have the same error in a similar MAC with python 3.9.13. It seems to be something related to statsmodels as well.

Thank you!

**Comment by bernhard-kaindl** [comment]
Unfortunately, I get the same result.

**Comment by JavierEscobarOrtiz** [comment]
Did you try python 3.8?

**Comment by shivangp76** [comment]
I tried with python 3.8 and same error.

**Comment by JavierEscobarOrtiz** [comment]
Hello,

For skforecast 0.6.0 we will make statsmodels an optional requirement to avoid these problems.

If you want you can install version 0.6.0 from GitHub with:

pip install git+https://github.com/JoaquinAmatRodrigo/skforecast#master

It is stable and should work even with python 3.10 😄

Please, comment if you try it! Thanks

**Comment by shivangp76** [comment]
Just tried it and it seems to be working now. Thanks!

**Comment by JavierEscobarOrtiz** [comment]
Hello,

Statsmodels is now an optional requirement to avoid these problems in skforecast 0.6.0, read the installation guide in the [README](https://github.com/JoaquinAmatRodrigo/skforecast) for more details.
