### ISSUE TITLE
Make compatible with numpy 1.23.1?

### ISSUE THREAD

**Issue by tulbureandreit** [JoaquinAmatRodrigo/skforecast#288]
Hi,

TLDR, because of recent update of setuptools to 65.6.0, could we somehow make this compatible with numpy=1.23.1?

**Comment by JavierEscobarOrtiz** [comment]
Hello @tulbureandreit ,

Thanks for reaching out. We will update the requirements in the next version.

For now, if you install numpy=1.23.1, skforecast should work.

Javier

**Comment by tulbureandreit** [comment]
Hi. I tried it and it seems like it does not work. Because of statsmodels (?)

@JavierEscobarOrtiz

**Comment by JavierEscobarOrtiz** [comment]
Which python version are you using? Try python 3.9

**Comment by tulbureandreit** [comment]
I need to use 3.10 in the project. Is there anything specific to 3.9?

**Comment by tulbureandreit** [comment]
**poetry add numpy=1.23.4**

Updating dependencies
Resolving dependencies... (0.3s)

**Because skforecast (0.5.1) depends on numpy (>=1.20,<=1.23)
 and no versions of skforecast match >0.5.1,<0.6.0, skforecast (>=0.5.1,<0.6.0) requires numpy (>=1.20,<=1.23).
So, because python-translation depends on both skforecast (^0.5.1) and numpy (1.23.4), version solving failed.**

**Comment by JavierEscobarOrtiz** [comment]
Hello, the problem is statsmodels, it is not compatible with python 3.10.

For skforecast 0.6.0 we will make it an optional requirement to avoid these problems.

Please, install version 0.6.0 from GitHub with:

```bash
pip install git+https://github.com/JoaquinAmatRodrigo/skforecast#master
```

It is stable and should work with python 3.10 and numpy 1.23.1 😄 

Please, comment if it works! Thanks

**Comment by JavierEscobarOrtiz** [comment]
Hello,

Statsmodels is now an optional requirement to avoid these problems in skforecast 0.6.0, read the installation guide in the [README](https://github.com/JoaquinAmatRodrigo/skforecast) for more details.
