### ISSUE TITLE
How to save model after training

### ISSUE THREAD

**Issue by mcfboss** [JoaquinAmatRodrigo/skforecast#30]
Hello Joaquim,

Couldn´t find how to save the model to a file once is trained, so I can use it later to predict new values.

Is skforecast capable of doing that? and how?

Thank you very much for skforecast! is great!

**Comment by JoaquinAmatRodrigo** [comment]
Hi @mcfboss 

Yes, you can save skforecast models using pickle and joblib. I will add this info in the documentation :)
```
import pandas as pd
from skforecast.ForecasterAutoreg import ForecasterAutoreg
from sklearn.linear_model import LinearRegression
from joblib import dump, load

# Create forecaster
forecaster = ForecasterAutoreg(LinearRegression(), lags=3)
forecaster.fit(y=pd.Series(np.arange(50)))

# Save model
dump(forecaster, filename='forecaster.py')

# Load model
forecaster_loaded = load('forecaster.py')
forecaster_loaded
```

Let me know if this solves your problem

**Comment by mcfboss** [comment]
Thank you very much Joaquin! 
I´ll try it straight away!
