### ISSUE TITLE
Forecasting Future Unknown Data

### ISSUE THREAD

**Issue by yagmurn** [JoaquinAmatRodrigo/skforecast#316]
Hello,

I divided the data into three part: Train, validation and test. I used the backtesting forecaster and predicted the validation data. Then I obtained a rmse via predicted and validation data. Now, I want to predict the test data without giving the test data into the model using backtesting forecaster. I will calculate a rmse again. Then I will forecast the future unknown data. 
How can I do that?? 

Thank you.

**Comment by JavierEscobarOrtiz** [comment]
Hello @yagmurn,

> Now, I want to predict the test data without giving the test data into the model using backtesting forecaster. 

You can use `backtesting_forecaster` without refit to simulate this process. Here `data` represent all your dataset (train + validation + test). 

Check the [user guide](https://joaquinamatrodrigo.github.io/skforecast/latest/user_guides/backtesting.html#backtest) diagram of "Backtesting without refit".

```python
# Backtest forecaster
# ==============================================================================
metric, predictions_backtest = backtesting_forecaster(
                                   forecaster         = forecaster,
                                   y                  = data['y'],
                                   initial_train_size = len(data_train) + len(data_validation) ,
                                   steps              = 7,
                                   metric             = 'mean_squared_error',
                                   refit              = False,
                                   verbose            = True
                               )
```

> Then I will forecast the future unknown data.

For this, I will train the forecaster with all the data (train + validation + test) and then predict the following steps

```python
forecaster.fit(y=data['y'])

forecaster.predict(steps=7)
```

**Comment by yagmurn** [comment]
Should steps in the backtesting and prediction be the same? 
If I define the steps as len(data_test) in forecaster.predict(steps=7), is it logical?

**Comment by JavierEscobarOrtiz** [comment]
> Should steps in the backtesting and prediction be the same?

Yes, but the value of `steps` depends on your data update period. Backtesting is a way of simulating your fit/prediction cycle. In the end, predictions based on real values will be more accurate than predictions based on predicted values. If you do `predict(steps=len(data_test))` the recursive process can become long and it will affect your predictions.

**Comment by yagmurn** [comment]
Hi again,
I am using gridsearch to find parameters based on rmse using train and validation data and I am forecasting test data with the best parameters in the result_grid. But I want to select parameters also based on the performance in the forecasting step. How can I integrate rmse of prediction of test and real test value with different parameter combination of forecaster? I have tried to write a for loop but I failed. Please help me.

**Comment by JavierEscobarOrtiz** [comment]
Hello @yagmurn,

I don't understand the division of your dataset. Could you please add an example of the code?

**Comment by yagmurn** [comment]
> Hello @yagmurn,
> 
> I don't understand the division of your dataset. Could you please add an example of the code?

Thank you, I solved that problem. 

I have a new question. I am trying to apply shap to support vector regression with linear kernel like below:

X_train, y_train = forecaster.create_train_X_y(
                        y    = weightedavg_test['trend'][:-35],
                        exog = weightedavg_test[['trend_decompose','trend_seasonal','trend_residual','temp_ist','buh_ist','prec_ist' ]][:-35]
                    )

import shap
shap_values = shap.KernelExplainer(forecaster.predict, X_train).shap_values(X_train)
shap.summary_plot(shap_values,X_train, plot_type="bar")

However, I received an error like that: "The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()". How can I overcome this error?
