### ISSUE TITLE
How to get In-sample forecast ( Train data) ? 

### ISSUE THREAD

**Issue by arcgolatkar** [JoaquinAmatRodrigo/skforecast#320]
Is there a way to get the forecast on training data?

**Comment by JavierEscobarOrtiz** [comment]
Hello @arcgolatkar ,

There is a good example in the docs, [link](https://joaquinamatrodrigo.github.io/skforecast/latest/user_guides/backtesting.html#predictions-on-training-data)

As you can see, there are 2 methods. One uses `backtesting_forecsater` and the other uses `fit` and `predict`. Both are returning the same results.
