### ISSUE TITLE
Question: forecaster.predict is not same as backtesting_forecaster predictions 

### ISSUE THREAD

**Issue by relakuman** [JoaquinAmatRodrigo/skforecast#321]
Hello
I have a question. Why is the forecast value different even if the last_window data of forecaster.predict and the initial_train_data of backtesting_forecaster are set to be the same period? (using same forecaster)
Did I miss anything?

**Comment by JoaquinAmatRodrigo** [comment]
Hi @relakuman,

Could you add an example of the code and results?

Thanks!

**Comment by relakuman** [comment]
Hi. I uploaded sample and results on my following github page.
https://github.com/relakuman/skforecast/tree/main

**Comment by JoaquinAmatRodrigo** [comment]
Hi @relakuman ,

The pandas Series or DataFrame used as **exog** in `predict()` must start one step ahead from the end of **last_window**. In your case, it would be:

```
steps = 91
predictions_steps = forecaster.predict(
    last_window = data[:end_validation]["y"],
    exog = data['2020-04-01':][exog_variables],
    steps=steps
)

predictions_steps.head()
```

Let us know if this solves the problem.

**Comment by JavierEscobarOrtiz** [comment]
Hi @relakuman 

In addition, if you want to continue using your variables, adding the time to your dates solves the problem.

```python
# Split train-val-test
# ==============================================================================
end_train = '2019-12-31 23:59:59'
end_validation = '2020-03-31 23:59:59'
end_test = '2020-06-30 23:59:59'

# Predict
steps = 91
predictions_steps = forecaster.predict(
    last_window = data[:end_validation]["y"],
    exog = data[end_validation:end_test][exog_variables],
    steps=steps
)

predictions_steps.head()
```
