### ISSUE TITLE
Predict future values with SARIMAX

### ISSUE THREAD

**Issue by orlandoap01** [JoaquinAmatRodrigo/skforecast#327]
Hi,

Is it possible to also predict future values with the implemented SARIMA model? I'm using it as a comparison method based on the backtest predictions and grid_search but not sure if it can also be used to predict into the future (the equivalent to .predict for the autoregressive forecaster).

Thanks

**Comment by JavierEscobarOrtiz** [comment]
Hello @orlandoap01,

Currently, a forecaster based on an ARIMA model has not been developed in Skforecast. You can always take the output of `grid_search_sarimax` and use any ARIMA API, for example [sarimax statsmodels](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.html) to train the model.

On the other hand, in Skforecast 0.7.0 we have created a forecaster based on ARIMA models that follows the standard API of the library, `ForecasterSarimax`. We expect to release this version in the next few days, we will ping you! 😄
