### ISSUE TITLE
 shap to support vector regression with linear kernel

### ISSUE THREAD

**Issue by JoaquinAmatRodrigo** [JoaquinAmatRodrigo/skforecast#330]
I am trying to apply shap to support vector regression with linear kernel like below:

X_train, y_train = forecaster.create_train_X_y(
                        y    = weightedavg_test['trend'][:-35],
                        exog = weightedavg_test[['trend_decompose','trend_seasonal','trend_residual','temp_ist','buh_ist','prec_ist' ]][:-35]
                    )

import shap
shap_values = shap.KernelExplainer(forecaster.predict, X_train).shap_values(X_train)
shap.summary_plot(shap_values,X_train, plot_type="bar")

However, I received an error like that: "The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()". How can I overcome this error?

_Originally posted by @yagmurn in https://github.com/JoaquinAmatRodrigo/skforecast/issues/316#issuecomment-1385832376_

**Comment by JavierEscobarOrtiz** [comment]
Hello @yagmurn, could you please add your data? Without it and the full code it is hard to replicate 😄 

Thank you!

**Comment by yagmurn** [comment]
[data_code.zip](https://github.com/JoaquinAmatRodrigo/skforecast/files/10455758/data_code.zip)
Here you can find the data and code. Thank you for your effort :)

**Comment by JavierEscobarOrtiz** [comment]
Hello @yagmurn,

I think this is more related to `shap`, I didn't use a lot this library but it looks like you have to pass the `predict` method of the regressor to the `KernelExplainer`instead of forecaster `predict` method. Try this:

```python
import shap

explainer = shap.KernelExplainer(forecaster_xg.regressor.predict, X_train)
shap_values = explainer.shap_values(X_train)

shap.summary_plot(shap_values, X_train, plot_type="bar")
```

You should get something like this:

![imagen](https://user-images.githubusercontent.com/95030312/213448502-d3dd1033-ca83-4e63-a5c2-c00534454d7e.png | width=100)

**Comment by yagmurn** [comment]
Thank you @JavierEscobarOrtiz  for your response. It worked :)
