### ISSUE TITLE
MultiVariate backtesting

### ISSUE THREAD

**Issue by AVPokrovsky** [JoaquinAmatRodrigo/skforecast#338]
Hi, I don't see backtesting_forecaster_multivariate in documentation. Can I use backtesting_forecaster_multiseries?

I tried backtesting_forecaster_multiseries with forecaster = ForecasterAutoregMultiVariate. No error, but I am not sure that is correct.

**Comment by JavierEscobarOrtiz** [comment]
Hello @AVPokrovsky, 

Yes you are correct. You should use `backtesting_forecaster_multiseries` for `ForecasterAutoregMultiVariate`.

Check the user guide for an example of how to use it:

https://joaquinamatrodrigo.github.io/skforecast/latest/user_guides/multivariate-forecasting.html#backtesting-multivariate

**Comment by AVPokrovsky** [comment]
Thank you. 
Can I use grid_search_forecaster_multiseries for ForecasterAutoregMultiVariate?

**Comment by JavierEscobarOrtiz** [comment]
Yes. The documentation has an example of `random_search_forecaster_multiseries`, but the idea is the same and the API is quite similar. 😄 

Dcoumentation: https://joaquinamatrodrigo.github.io/skforecast/latest/user_guides/multivariate-forecasting.html#hyperparameter-tuning-and-lags-selection-multivariate

API `grid_search_forecaster_multiseries`: https://joaquinamatrodrigo.github.io/skforecast/latest/api/model_selection_multiseries.html#skforecast.model_selection_multiseries.model_selection_multiseries.grid_search_forecaster_multiseries
