### ISSUE TITLE
ImportError: cannot import name 'dataclass_transform' from 'typing_extensions'

### ISSUE THREAD

**Issue by MatthiasCami8** [JoaquinAmatRodrigo/skforecast#361]
I have the following error in Databricks:

`
ImportError: cannot import name 'dataclass_transform' from 'typing_extensions' (/databricks/python/lib/python3.9/site-packages/typing_extensions.py)`

when importing

`from skforecast.model_selection import grid_search_forecaster`

**Comment by JoaquinAmatRodrigo** [comment]
Hi @MatthiasCami8 
What was the reason for the error?

Thanks!

**Comment by MatthiasCami8** [comment]
Hi Joaquin,

You need typing-extensions version of at least 4.0.0 to have the 'dataclass_transform'.

And I pip installed version 4.5.0, but Databricks has some set libraries (like typing_extensions) which you can't overwrite in the notebook itself, but have to change directly in the compute library. Doing this solved the issue.

**Comment by JoaquinAmatRodrigo** [comment]
Thanks for the info!
