### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AVPokrovsky** [JoaquinAmatRodrigo/skforecast#365]
Hi, is 0.7.0 documentation available? I see only 0.6.0....

**Comment by JoaquinAmatRodrigo** [comment]
Hi @AVPokrovsky,
The docs for 0.7.0 is now abailable:  https://joaquinamatrodrigo.github.io/skforecast/0.7.0/index.html

**Comment by AVPokrovsky** [comment]
Thanks
