### ISSUE TITLE
SARIMAX 

### ISSUE THREAD

**Issue by AVPokrovsky** [JoaquinAmatRodrigo/skforecast#371]
Hi, I see in release changed "model_selection_statsmodels is deprecated in favor of ForecasterSarimax and model_selection_sarimax".
The old one "model_selection_statsmodels" is used in user guides. I tried to change, but in seems parameters are different. Could you provide new guides?

**Comment by JavierEscobarOrtiz** [comment]
Hello @AVPokrovsky 

You have the user_guide of the new implementation, `ForcasterSarimax`, available here:

https://joaquinamatrodrigo.github.io/skforecast/latest/user_guides/forecasting-sarimax-arima.html

**Comment by AVPokrovsky** [comment]
Of cause, I will give feedback if any.
Is there any changes for backtesting and grid_search? 
I don't see changes in the user guides...
from skforecast.model_selection_statsmodels import backtesting_sarimax
from skforecast.model_selection_statsmodels import grid_search_sarimax

**Comment by AVPokrovsky** [comment]
I see now new backtesting and grid_search in SARIMAX and ARIMA forecasters chapter. I looked before in Backtesting SARIMAX and ARIMA models and Grid search SARIMAX and ARIMA models chapters...

**Comment by AVPokrovsky** [comment]
I moved to new version. It's Ok.
