### ISSUE TITLE
Need Help to Double Check: when training the model and using the grid-serach

### ISSUE THREAD

**Issue by kennis222** [JoaquinAmatRodrigo/skforecast#373]
Hello Developers,

I would like to confirm that when I use direct or recursive strategy to train the model and use the grid search, I can choose the 
`
  refit = True,
  return_best = True,
fixed_train_size = True,
`
I can clearly see that model is trained using cross-validation method and rolling origin (rolling window). However, I would like to confirm that I when conduct the model to forecast, does the model also used the  rolling origin (rolling window) to predict, which means that does the model use the most recent data to predict? 

Why I ask is because I would like to make sure that I finally use the most recent data to predict : ) If not, how I can fix the it?

Thanks.

**Comment by JavierEscobarOrtiz** [comment]
Hello @kennis222 

As you said, when you are validating your model during the grid search, the strategy followed is what you mention that is represented in the gif in the documentation that you have probably already seen:

https://joaquinamatrodrigo.github.io/skforecast/0.7.0/img/backtesting_refit_fixed_train_size.gif

Once the grid_search is finished, as you are using `return_best = True`, the model is trained with the complete series (and best lags/hyperparameters) you have used in the grid_search. This is the same you will obtain as with the `fit()` method:

```python
forecaster.fit(y=y) # full series
```

Therefore, when it comes to forecasting, you will use all the information, the complete series.

Hope it helps!

**Comment by kennis222** [comment]
Thank you for the clarification. After using the grid search, if I would like to conduct the model by using the most recent data, I think I need to try to change the source codes. What specific module I use is ForecasterAutoregMultiVariate. If I want to change, does it make sense to modify nearby here `self.training_range = preprocess_y(y=series[self.level])[1][[0, -1]]` ?

**Comment by JoaquinAmatRodrigo** [comment]
Hi @kennis222,
Do you mean to retrain the model with the whole data set?
You can always train the forecaster with new data using the `.fit()` method. This will not affect any of the hyperparameters nor the lags used.

**Comment by kennis222** [comment]
It works, thank you.
