### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by astrojuanlu** [JoaquinAmatRodrigo/skforecast#376]
Having a Code of Conduct (CoC for short) is recognised as a step towards having good community standards:

https://github.com/JoaquinAmatRodrigo/skforecast/community

GitHub makes it easy to add a CoC called the Contributor Covenant, which looks like this:

https://www.contributor-covenant.org/version/2/0/code_of_conduct/

Some Python projects have more complex CoCs because they're derived from the one by the Python Software Foundation, which draws inspiration from many sources:

https://www.python.org/psf/conduct/

![image](https://user-images.githubusercontent.com/316517/228052784-d40b3c9c-f98b-42c7-96df-7bf19f91242b.png)

But probably for a relatively small project like `skforecast`, hitting https://github.com/JoaquinAmatRodrigo/skforecast/community/code-of-conduct/new?template=contributor-covenant should be fine.

**Comment by astrojuanlu** [comment]
Closed in gh-380 🎉 Thank you folks!

**Comment by JavierEscobarOrtiz** [comment]
Thanks for the suggestion @astrojuanlu 😄
