### ISSUE TITLE
Consider applying for pyOpenSci open peer review

### ISSUE THREAD

**Issue by astrojuanlu** [JoaquinAmatRodrigo/skforecast#377]
pyOpenSci https://www.pyopensci.org/about-peer-review/ is modeled after rOpenSci and offers a community-led, open peer review process for scientific Python packages. Maybe they would be happy to review skforecast!

(See https://github.com/pyOpenSci/pyopensci.github.io/issues/150)

**Comment by astrojuanlu** [comment]
Scope: https://www.pyopensci.org/software-peer-review/about/package-scope.html

**Comment by JoaquinAmatRodrigo** [comment]
Hi, 
This issue has been inactive for a while, so we're closing it to keep the repo tidy. If needed, feel free to reopen or create a new issue.

Thanks!
