### ISSUE TITLE
Consider adopting a code autoformatter

### ISSUE THREAD

**Issue by astrojuanlu** [JoaquinAmatRodrigo/skforecast#379]
One of the most idiosyncratic features, at first sight, of the `skforecast` codebase is the liberal use of whitespace, see for example:

https://github.com/JoaquinAmatRodrigo/skforecast/blob/47a0fc0f023393a423f1996e13f5337c208a6636/skforecast/model_selection/tests/test_backtesting_forecaster.py#L51-L66

Nowadays there's a trend of using automatic code formatters, like [Black](https://black.readthedocs.io/), which apply a uniform code style automatically.

It's important to note that the point of these tools is to save time for developers by completely giving up formatting solutions. This has pros and cons:

- Pros: You don't have to make decisions about code formatting ever again.
- Cons: You don't _get_ to decide the code formatting ever again 🙃 

There are intermediate solutions that are not so opinionated, like [yapf](https://pypi.org/project/yapf/), that allow some configuration. But still, it's unlikely that you can configure the automated tool to do _exactly_ what you'd want in all cases.

I personally find tools like Black quite liberating, by freeing me from tweaking the style of my code even if sometimes I don't quite like the result. However, I'd also understand if the skforecast maintainers decide to not adopt one.

To give you an idea of what this would mean, here's the result of applying `black .` to `skforecast`:

```
> git diff --stat | tail -n1
 164 files changed, 24374 insertions(+), 17492 deletions(-)
```

**Comment by JoaquinAmatRodrigo** [comment]
Hi, 
This issue has been inactive for a while, so we're closing it to keep the repo tidy. If needed, feel free to reopen or create a new issue.

Thanks!
