### ISSUE TITLE
Predictions not using time as index

### ISSUE THREAD

**Issue by epeasang** [JoaquinAmatRodrigo/skforecast#385]
Hi, im training a model for times series forecasting. My dataset have quarter hour measurements of the energy. First i maded a grid search for hyperparameters. This turns out that 96 is the best value for the lag variable. After that, I maked a predict using steps as 96. 

Predictions index are starting on 96 and increasing by 1 instead of giving me the date and the hour. So when i tried to represent predictions vs real data its gives me the error no one of the (96,97...) are in the index. I've been doing like so:

fig, ax = plt.subplots(figsize=(12, 3.5))
datos.loc[predictions.index, 'Energy'].plot(linewidth=2, label='test', ax=ax)
predictions.plot(linewidth=2, label='predicción', ax=ax)
ax.set_title('Prediccion vs real')
ax.legend();

How can i solve that? When i predict data i will need to change index to a data time?

Thanks in advance.

**Comment by JavierEscobarOrtiz** [comment]
Hello @epeasang 

Without seeing the data is a bit difficult to imagine the problem but probably you need to define a pandas DatetimeIndex with frequency to keep the date time index. Something like:

```python
data = pd.read_csv(url)
data['date'] = pd.to_datetime(data['date'], format='%Y/%m/%d')
data = data.set_index('date')
data = data.asfreq('MS')
data
```

Remember that there are some constraints to associating a pandas frequency to your time series, look at this [issue](https://github.com/JoaquinAmatRodrigo/skforecast/issues/81).

This user guide may help you:

https://joaquinamatrodrigo.github.io/skforecast/latest/user_guides/input-data.html

Hope it helps!

**Comment by epeasang** [comment]
Okey so i checked if i had missing values and have them, so i decided to fill de missing values with 0.

thanks for your fast response!
