### ISSUE TITLE
Feature selection

### ISSUE THREAD

**Issue by AVPokrovsky** [JoaquinAmatRodrigo/skforecast#387]
Hi, do you have any tools for feature selection?

https://scikit-learn.org/stable/modules/feature_selection.html#

**Comment by JoaquinAmatRodrigo** [comment]
Hi,
@AVPokrovsky, skforecast allows the selection of lags (autoregressive features) by using grid and bayesian search but not for the exogenous.

https://joaquinamatrodrigo.github.io/skforecast/latest/user_guides/hyperparameter-tuning-and-lags-selection.html

**Comment by AVPokrovsky** [comment]
Ok, Thanks.
Actually I wasn't asking about exogenous. I am trying Multivariate forecasting and would like to know which input series improve the results.

**Comment by AVPokrovsky** [comment]
Hi, could you advice how to do it if it is possible?
May be some code examples available....

1.13.6. Feature selection as part of a pipeline
