### ISSUE TITLE
Prophet

### ISSUE THREAD

**Issue by AVPokrovsky** [JoaquinAmatRodrigo/skforecast#391]
Hi, is Prophet supported?
I see they declare sklearn API.

https://facebook.github.io/prophet/docs/quick_start.html

**Comment by JoaquinAmatRodrigo** [comment]
Hi @AVPokrovsky, thabnks for using skforecast.

Although prophet follows the naming `fit` and `predict`, the required inputs are not the standard y, X. So currently skforcast doesn't support it.
