### ISSUE TITLE
Forecasting SARIMAX

### ISSUE THREAD

**Issue by JorgeGomes72** [JoaquinAmatRodrigo/skforecast#410]
Hello,
regarding this:

https://skforecast.org/0.7.0/user_guides/forecasting-sarimax-arima.html#libraries

i have tried to reproduce exactly the same code but i had an error at this point: 
```
# Create and fit ForecasterSarimax
# ======================================================================================
forecaster = ForecasterSarimax(
                 regressor=ARIMA(order=(12, 1, 1), seasonal_order=(0, 0, 0, 0), maxiter=200),
             )

forecaster.fit(y=data_train)
forecaster
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 7
      1 # Create and fit ForecasterSarimax
      2 # ======================================================================================
      3 forecaster = ForecasterSarimax(
      4                  regressor=ARIMA(order=(12, 1, 1), seasonal_order=(0, 0, 0, 0), maxiter=200),
      5              )
----> 7 forecaster.fit(y=data_train)
      8 forecaster

File ~\Anaconda3\lib\site-packages\skforecast\ForecasterSarimax\ForecasterSarimax.py:286, in ForecasterSarimax.fit(self, y, exog)
    283     self.index_freq = y.index.step
    285 self.last_window = y.copy()
--> 286 self.extended_index = self.regressor.arima_res_.fittedvalues.index.copy()
    287 self.params = self.regressor.get_params(deep=True)

AttributeError: 'numpy.ndarray' object has no attribute 'index'
```

![image](https://user-images.githubusercontent.com/57633568/234091075-fd046732-aac8-4d17-9f0c-e9df82777ade.png)
![image](https://user-images.githubusercontent.com/57633568/234091204-ae5906d4-3fb5-48da-ab5d-32bee2310785.png)

My version of skforecast==0.7.0

Could you help, please?

Thank you,
JG

**Comment by JoaquinAmatRodrigo** [comment]
Hi @JorgeGomes72,
Thanks for using the new ForecasterSarimax.
Could you add the whole sequence of code you are using? This way we can be sure we are executing exatly the same.
What operation system and Python version are you using?

Thanks!

**Comment by JorgeGomes72** [comment]
Hello,
i just repeat the code in your article.

i am using Windows 10 Pro (x64) with Anaconda jupyter-lab, python version 3.8.8.

i can try another instance of python, without Anaconda.

`
## Libraries
## =============================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from skforecast.ForecasterSarimax import ForecasterSarimax
from skforecast.model_selection_sarimax import backtesting_sarimax
from skforecast.model_selection_sarimax import grid_search_sarimax
from pmdarima import ARIMA
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings('ignore')

### Download data
### =================================
url = ('https://raw.githubusercontent.com/JoaquinAmatRodrigo/skforecast/master/data/h2o.csv')
data = pd.read_csv(url, sep=',', header=0, names=['y', 'datetime'])
#print(data)

### Data preprocessing
### ====================================
data['datetime'] = pd.to_datetime(data['datetime'], format='%Y/%m/%d')
data = data.set_index('datetime')
data = data.asfreq('MS')
data = data['y']
data = data.sort_index()
#print(data)

### Train-test dates
### =======================================
end_train = '2005-06-01 23:59:00'
print(f"Train dates : {data.index.min()} --- {data.loc[:end_train].index.max()}  (n={len(data.loc[:end_train])})")
print(f"Test dates  : {data.loc[end_train:].index.min()} --- {data.loc[:].index.max()}  (n={len(data.loc[end_train:])})")
data_train = data.loc[:end_train]
data_test  = data.loc[end_train:]

### Plot
### ======================================
fig, ax=plt.subplots(figsize=(7, 3))
data_train.plot(ax=ax, label='train')
data_test.plot(ax=ax, label='test')
ax.legend();


### Create and fit ForecasterSarimax
### ============================================
forecaster = ForecasterSarimax(
                 regressor=ARIMA(order=(12, 1, 1), seasonal_order=(0, 0, 0, 0), maxiter=200),
             )

forecaster.fit(y=data_train)
forecaster

`

Thank you.
Regards,
JG

**Comment by JavierEscobarOrtiz** [comment]
Hello @JorgeGomes72,

Sorry, we need full information about your environment because we are not able to reproduce the error.

Could you please install the following package:

```bash
pip install session_info
```

And then, in the jupyter notebook, execute:

```python
import session_info
session_info.show(html=False)
```

It should return something like this:

```
-----
matplotlib          3.7.0
networkx            3.0
pandas              1.5.3
session_info        1.0.0
-----
IPython             8.10.0
jupyter_client      7.3.4
jupyter_core        5.2.0
-----
Python 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0]
Linux-5.15.0-69-generic-x86_64-with-glibc2.31
-----
Session information updated at 2023-04-02 18:01
```

**Comment by JorgeGomes72** [comment]
Hello,
it seems to be a Anaconda problem...i closed Anaconda and tried  jupyter-lab from another python3.8 instance (C:\python38).
Now it is working!

Skforecast version: 0.7.0 
Python version: 3.8.0 

Peraphs the problem was python version?

Thank you.
JG

**Comment by JavierEscobarOrtiz** [comment]
Nice! Not sure, maybe it was the pmdarima version. if you find the problem again, let us know!

**Comment by JavierEscobarOrtiz** [comment]
Hello @JorgeGomes72,

You are using a deprecated module. Use these functions from `model_selection_sarimax` module:

```python


# Libraries
# ======================================================================================
from skforecast.ForecasterSarimax import ForecasterSarimax
from skforecast.model_selection_sarimax import backtesting_sarimax
from skforecast.model_selection_sarimax import grid_search_sarimax
```

User guide backtesting: https://skforecast.org/latest/user_guides/forecasting-sarimax-arima.html#backtesting
User guide hyperparameters: https://skforecast.org/latest/user_guides/forecasting-sarimax-arima.html#model-tunning

Hope it helps!

**Comment by JorgeGomes72** [comment]
oh...
you are reason, i am using this:
from skforecast.ForecasterSarimax import ForecasterSarimax
from skforecast.model_selection_statsmodels import backtesting_sarimax
from skforecast.model_selection_statsmodels import grid_search_sarimax

after by lunch break i will test, thank you!
JG
