### ISSUE TITLE
grid_search_forecaster - metric

### ISSUE THREAD

**Issue by AVPokrovsky** [JoaquinAmatRodrigo/skforecast#420]
Hi, as I understand, it is possible to set the list of different metrics. How does it find the best results using several metrics? Summarizing the metrics?

**Comment by JavierEscobarOrtiz** [comment]
Hello @AVPokrovsky

If you mean when optimizing hyperparameters, as the documentation says:

"It should be noted that when multiple metrics are specified, these functions will select the best model based on the **first metric in the list**."

https://skforecast.org/latest/user_guides/hyperparameter-tuning-and-lags-selection.html#compare-multiple-metrics
