### ISSUE TITLE
Why does the model predict like this?

### ISSUE THREAD

**Issue by IgnacioRodriguez98** [JoaquinAmatRodrigo/skforecast#426]
I am doing tests with models to predict energy demand, with a dataset of 1664 daily data that covers 2014-09-10 - 2019-03-31, the problem is that when trying to predict it the model predicts the follow.

https://i.stack.imgur.com/gGa75.png

Any idea why the predictions are "normalized"?

This is the code

```train_size = int(len(data) * 0.8)
test_size = len(data) - train_size
data_train, data_test = data[0:train_size], data[train_size:len(data)]
steps = test_size


forecaster = ForecasterAutoreg(
                regressor = RandomForestRegressor(random_state=123,n_jobs=-1),
                lags =365
             )

forecaster.fit(y=data_train['y'])
forecaster

predictions = forecaster.predict(steps=steps)

data_train['y'].plot(ax=ax, label='train')
data_test['y'].plot(ax=ax, label='test')
predictions.plot(ax=ax, label='predicciones')
plt.title("Random Forest 2021-2022")
ax.legend()

**Comment by mathisdrn** [comment]
data_test['y'].plot(ax=ax, label='test')
imply that your dataframe index are date but you way of creating X_train, X_test suggest otherwise :
data_train, data_test = data[0:train_size], data[train_size:len(data)]

Could you check your input data with create_train_X_y ?
