### ISSUE TITLE
MLPRegressor Bayesian search

### ISSUE THREAD

**Issue by AVPokrovsky** [JoaquinAmatRodrigo/skforecast#427]
Hi, can I search hidden_layer_sizes for MLPRegressor using Bayesian search?
If yes, how can I write search_space code for it?

E.g, I use for grid search param_grid = {'hidden_layer_sizes':[[50,50], [70,50], [100,50], [100,100],[100],[100,50,30],[256,256],[256,256,128]].
I would like to write something like this for Bayesian search_space

**Comment by AVPokrovsky** [comment]
I write like this. It starts to work, but is it correct?

        def search_space(trial):
         search_space  = {'hidden_layer_sizes'     : [trial.suggest_int('hidden_layer_sizes', 20, 256),trial.suggest_int('hidden_layer_sizes', 20, 256)]
                                                                         
                         }            
         return search_space

**Comment by JavierEscobarOrtiz** [comment]
Hello @AVPokrovsky, for me seems good
