### ISSUE TITLE
Error with forecaster model in production when providing `exog`

### ISSUE THREAD

**Issue by davidusb-geek** [JoaquinAmatRodrigo/skforecast#445]
I have a forecaster model that has already been fitted. 
My model was fitted using exogenous data known in the future.
Then I just want to make predictions in production when providing last window data and the known exogenous data.
How to do this?

My current approach is like this:
```
predictions = self.forecaster.predict(steps=self.num_lags, 
                                      last_window=data_last_window[self.var_model],
                                      exog=data_last_window.drop(self.var_model, axis=1))
```
But I keep getting this error:
```
Exception has occurred: ValueError
To make predictions `exog` must start one step ahead of `last_window`.
```

In my test my DataFrame looks this this:
![image](https://github.com/JoaquinAmatRodrigo/skforecast/assets/32926550/97affab3-be65-4cc1-9671-b81f9378a2e1)

And the exact error message is this:
```
Exception has occurred: ValueError
To make predictions `exog` must start one step ahead of `last_window`.
    `last_window` ends at : 2022-03-03 21:00:00+00:00.
    `exog` starts at      : 2022-03-01 21:00:00+00:00.
     Expected index       : 2022-03-03 21:30:00+00:00.
```
But my data does not goes beyond `2022-03-03 21:00:00+00:00`, so how are we supposed to pass the exog data in this case?
This seems like a bug right?

**Comment by JoaquinAmatRodrigo** [comment]
Hello @davidusb-geek 

Thank you for using skforecast!

Based on my understanding of your code, the initial prediction using skforecast will occur at 2022-03-03 21:30:00+00:00, which is one step ahead of the last observation in the previous window. Consequently, the exog variable should start at 2022-03-03 21:30:00+00:00 and extend for the same number of steps as the predictions. It's important to note that the exog variable always aligns with the forecasted horizon.

I hope this clarifies the process for you. If you have any further questions, feel free to ask!

**Comment by davidusb-geek** [comment]
It seems that I was very tired yesterday when I opened this issue.
Yes it is clear now. So the last window `y` data is used to build the predictions using my fixed number of lags and then I provide `exog` with the DateTimeIndex of the future steps. So the `exog` index should always start after the last index of last window `y` data.
Thanks for clarifying this.
