### ISSUE TITLE
Suggestion of improving the allow_incomplete_fold

### ISSUE THREAD

**Issue by kennis222** [JoaquinAmatRodrigo/skforecast#447]
Hi developers,

The strategy of setting the allow_incomplete_fold may need to be improved.  Based on the notes from source code, 
"allow_incomplete_fold : bool, default `True`
The last test set is allowed to be incomplete if it does not reach `steps`
observations. Otherwise, the latest observations are discarded. "

Since the default of setting is `True`, I change from `True`  to `False`. After changing, the results is shown as below,
![Screenshot 2023-05-24 at 10 23 30](https://github.com/JoaquinAmatRodrigo/skforecast/assets/48114411/2cce8b1b-4f99-4eb7-b023-3bba84eadeb5)

I use the backtest as an example, and the  `steps` I set is 12. In principle, the number of the folds should be 9, and it drops the last one since the setting the allow_incomplete_fold as `FALSE`. However, based on the split and in the 8th fold, the last fold only includes 6 observations. Thus, the strategy of setting the allow_incomplete_fold may not be suitable by only dropping the latest observations.

Thanks

**Comment by JavierEscobarOrtiz** [comment]
Hello @kennis222,

Thank you very much for your contribution. Could you please add the code of your example? The forecaster and the type of backtesting that you are using.

**Comment by kennis222** [comment]
`self._forecaster = ForecasterAutoregMultiVariate(
            regressor = self.selected_model,
            level = self.level,
            lags = self.lags,
            steps  = self.forecasted_steps,
            weight_func = self.custom_weights #None
        )`



Sure, here is the code:
`backtesting_forecaster_multiseries(
                forecaster  = self._forecaster,
                levels = self.level,
                series = self.data_part,
                exog = self.exog_part,
                steps = self.forecasted_steps,
                metric = self.metrics,
                initial_train_size = self.initial_train_size,
                fixed_train_size = True,
                refit = True,
                verbose = True,
        )`

The version I use so far is Version0.6.

**Comment by JavierEscobarOrtiz** [comment]
Hi @kennis222, The `allow_incomplete_fold` argument was introduced in version 0.8.0. Please try updating skforecast and let us know if this solves the problem.
