### ISSUE TITLE
attribute/type error: predict() method returning np.ndarray

### ISSUE THREAD

**Issue by harpreet-s-paul** [JoaquinAmatRodrigo/skforecast#475]
I try running backtesting on a sarimax forecaster...
```
best_sarimax_forecaster_total_defaults_increasing_training_size = ForecasterSarimax(
regressor = ARIMA(order=(2, 1, 2), seasonal_order=(1, 0, 0, 12), maxiter=50, trend=None),)
```

```
results_sarimax_total_defaults_increasing_train_size = backtesting_sarimax(
forecaster         = best_sarimax_forecaster_total_defaults_increasing_training_size,
y = data_lag_12_imputed['total_defaults'],
exog = data_lag_12_imputed.iloc[:,3:],
initial_train_size = 120,
fixed_train_size   = False,
steps              = 12,
metric             = ['mean_absolute_error', 'mean_absolute_percentage_error'],
refit              = True,
interval = [2.5, 97.5])
```
... and get the following error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[51], line 4
      1 best_sarimax_forecaster_total_defaults_increasing_training_size = ForecasterSarimax(
      2 regressor = ARIMA(order=(2, 1, 2), seasonal_order=(1, 0, 0, 12), maxiter=50, trend=None),)
----> 4 results_sarimax_total_defaults_increasing_train_size = backtesting_sarimax(
      5 forecaster         = best_sarimax_forecaster_total_defaults_increasing_training_size,
      6 y = data_lag_12_imputed['total_defaults'],
      7 exog = data_lag_12_imputed.iloc[:,3:],
      8 initial_train_size = 120,
      9 fixed_train_size   = False,
     10 steps              = 12,
     11 metric             = ['mean_absolute_error', 'mean_absolute_percentage_error'],
     12 refit              = True,
     13 interval = [2.5, 97.5])

File ~\.conda\envs\forecasting_default_rate\lib\site-packages\skforecast\model_selection_sarimax\model_selection_sarimax.py:469, in backtesting_sarimax(forecaster, y, steps, metric, initial_train_size, fixed_train_size, exog, refit, alpha, interval, verbose)
    464     raise TypeError(
    465         f'`refit` must be boolean: `True`, `False`.'
    466     )
    468 if refit:
--> 469     metrics_values, backtest_predictions = _backtesting_sarimax_refit(
    470         forecaster          = forecaster,
    471         y                   = y,
    472         steps               = steps,
    473         metric              = metric,
    474         initial_train_size  = initial_train_size,
    475         fixed_train_size    = fixed_train_size,
    476         exog                = exog,
    477         alpha               = alpha,
    478         interval            = interval,
    479         verbose             = verbose
    480     )
    481 else:
    482     metrics_values, backtest_predictions = _backtesting_sarimax_no_refit(
    483         forecaster          = forecaster,
    484         y                   = y,
   (...)
    491         verbose             = verbose
    492     )

File ~\.conda\envs\forecasting_default_rate\lib\site-packages\skforecast\model_selection_sarimax\model_selection_sarimax.py:170, in _backtesting_sarimax_refit(forecaster, y, steps, metric, initial_train_size, fixed_train_size, exog, alpha, interval, verbose)
    168         pred = forecaster.predict(steps=steps, exog=next_window_exog)
    169     else:
--> 170         pred = forecaster.predict_interval(
    171                    steps    = steps,
    172                    alpha    = alpha,
    173                    interval = interval,
    174                    exog     = next_window_exog,
    175                )
    177     backtest_predictions.append(pred)
    179 backtest_predictions = pd.concat(backtest_predictions)

File ~\.conda\envs\forecasting_default_rate\lib\site-packages\skforecast\ForecasterSarimax\ForecasterSarimax.py:662, in ForecasterSarimax.predict_interval(self, steps, last_window, last_window_exog, exog, alpha, interval)
    654 # Get following n steps predictions with intervals
    655 predicted_mean, conf_int = self.regressor.predict(
    656                                n_periods       = steps,
    657                                X               = exog,
    658                                alpha           = alpha,
    659                                return_conf_int = True
    660                            )
--> 662 predictions = predicted_mean.to_frame(name="pred")
    663 predictions['lower_bound'] = conf_int[:, 0]
    664 predictions['upper_bound'] = conf_int[:, 1]

AttributeError: 'numpy.ndarray' object has no attribute 'to_frame'
```
Then I try simply fitting a sarimax forecaster on some data...
```
sarimax_forecaster_default_rate = ForecasterSarimax(
regressor = ARIMA(order=(0, 1, 2), seasonal_order=(0, 0, 1, 12), maxiter=50, trend=None))

sarimax_forecaster_default_rate.fit(y = data_lag_12_imputed['default_rate'], exog = data_lag_12_imputed.iloc[:,3:-2])
```
... and call the predict method...
```
index = pd.date_range(start='2023-01-01', periods=12, freq='MS')
sarimax_forecaster_default_rate.predict(steps=12, exog=data_imputed.iloc[-12:,3:-2].set_index(index))
```
...but I get what seems to be a related error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[21], line 2
      1 index = pd.date_range(start='2023-01-01', periods=12, freq='MS')
----> 2 sarimax_forecaster_default_rate.predict(steps=12, exog=data_imputed.iloc[-12:,3:-2].set_index(index))

File ~\.conda\envs\forecasting_default_rate\lib\site-packages\skforecast\ForecasterSarimax\ForecasterSarimax.py:474, in ForecasterSarimax.predict(self, steps, last_window, last_window_exog, exog)
    468 predictions = self.regressor.predict(
    469                   n_periods = steps,
    470                   X         = exog
    471               )
    473 # Reverse the transformation if needed
--> 474 predictions = transform_series(
    475                   series            = predictions,
    476                   transformer       = self.transformer_y,
    477                   fit               = False,
    478                   inverse_transform = True
    479               )
    480 predictions.name = 'pred'
    482 return predictions

File ~\.conda\envs\forecasting_default_rate\lib\site-packages\skforecast\utils\utils.py:1160, in transform_series(series, transformer, fit, inverse_transform)
   1129 """      
   1130 Transform raw values of pandas Series with a scikit-learn alike transformer
   1131 (preprocessor). The transformer used must have the following methods: fit, transform,
   (...)
   1156 
   1157 """
   1159 if not isinstance(series, pd.Series):
-> 1160     raise TypeError(
   1161         (f"`series` argument must be a pandas Series. Got {type(series)}.")
   1162     )
   1164 if transformer is None:
   1165     return series

TypeError: `series` argument must be a pandas Series. Got <class 'numpy.ndarray'>.
```
Either way, it seems that somehow the predict method returns the wrong type of object.

**Comment by JavierEscobarOrtiz** [comment]
Hello @harpreet-s-paul,

I replicate your code with another dataframe and it works for me, I am using skforecast 0.8.1.

```python
# Libraries
# ======================================================================================
import pandas as pd
from skforecast.ForecasterSarimax import ForecasterSarimax
from pmdarima import ARIMA

# Download data
# ======================================================================================
url = (
    'https://raw.githubusercontent.com/JoaquinAmatRodrigo/skforecast/master/'
    'data/h2o_exog.csv'
)
data = pd.read_csv(
            url, sep=',', header=0, names=['datetime', 'y', 'exog_1', 'exog_2']
       )

# Data preprocessing
# ======================================================================================
data['datetime'] = pd.to_datetime(data['datetime'], format='%Y-%m-%d')
data = data.set_index('datetime')
data = data.asfreq('MS')
data = data.sort_index()
data.head(2)
```
| datetime            |        y |   exog_1 |   exog_2 |
|:--------------------|---------:|---------:|---------:|
| 1992-04-01 00:00:00 | 0.379808 | 0.958792 |  1.16603 |
| 1992-05-01 00:00:00 | 0.361801 | 0.951993 |  1.11786 |

```python
# Create and fit ForecasterSarimax
# ======================================================================================
forecaster = ForecasterSarimax(
                 regressor=ARIMA(order=(0, 1, 2), seasonal_order=(0, 0, 1, 12), maxiter=50, trend=None),
             )

forecaster.fit(y=data['y'], exog = data[['exog_1', 'exog_2']])
```

Here are two different alternatives for the predict method:

```python
# Method 1
# ======================================================================================
exog_predict = data[['exog_1', 'exog_2']].head(10).copy()
exog_predict.index = pd.date_range(start='2008-07-01', periods=10, freq='MS')

predictions = forecaster.predict(steps=5, exog=exog_predict)
predictions.head(3)
```
2008-07-01    0.836017
2008-08-01    0.837904
2008-09-01    0.779449
Freq: MS, Name: pred, dtype: float64

This is similar to your method but I change `index` to `idx` to avoid overwriting the pandas index method.

```python
# Method 2
# ======================================================================================
idx = pd.date_range(start='2008-07-01', periods=10, freq='MS')

predictions = forecaster.predict(steps=5, exog=data[['exog_1', 'exog_2']].head(10).set_index(idx))
predictions.head(3)
```
2008-07-01    0.836017
2008-08-01    0.837904
2008-09-01    0.779449
Freq: MS, Name: pred, dtype: float64

Hope it helps

**Comment by harpreet-s-paul** [comment]
Hey Javier,

I ran your code and only your code in a separate test notebook, and got the same error when calling the predict method. That suggests there is some problem with my environment, I think?

Below are the details of my conda environment:

Name                    Version                   Build  Channel
----------------------------------------------------------
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
alembic                   1.10.2                   pypi_0    pypi
anyio                     3.5.0            py39haa95532_0
appdirs                   1.4.4              pyhd3eb1b0_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0
asttokens                 2.0.5              pyhd3eb1b0_0
atomicwrites              1.4.1                    pypi_0    pypi
attrs                     22.1.0           py39haa95532_0
backcall                  0.2.0              pyhd3eb1b0_0
beautifulsoup4            4.11.1           py39haa95532_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
bottleneck                1.3.5            py39h080aedc_0
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotlipy                  0.7.0           py39h2bbff1b_1003
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cairo                     1.16.0            h63a05c6_1001    conda-forge
catboost                  1.1.1            py39hcbf5309_2    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h2bbff1b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
cmaes                     0.9.1                    pypi_0    pypi
cmdstan                   2.29.2               hc4b6281_2    conda-forge
cmdstanpy                 1.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6            py39haa95532_0
colorlog                  6.7.0                    pypi_0    pypi
comm                      0.1.2            py39haa95532_0
console_shortcut          0.1.1                         4
contourpy                 1.0.5            py39h59b6b97_0
convertdate               2.4.0              pyhd8ed1ab_0    conda-forge
coverage                  7.2.2                    pypi_0    pypi
cryptography              39.0.1           py39h21b164f_0
cycler                    0.11.0             pyhd3eb1b0_0
cython                    0.29.33          py39hd77b12b_0
debugpy                   1.5.1            py39hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
entrypoints               0.4              py39haa95532_0
ephem                     4.1.2            py39h2bbff1b_0
execnet                   1.9.0                    pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0
expat                     2.5.0                h63175ca_1    conda-forge
flit-core                 3.8.0            py39haa95532_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               ha860e81_0
fribidi                   1.0.10               h8d14728_0    conda-forge
fsspec                    2023.4.0           pyh1a96a4e_0    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
getopt-win32              0.1                  h8ffe710_0    conda-forge
giflib                    5.2.1                h8cc25b3_3
glib                      2.69.1               h5dc1a3c_2
graphite2                 1.3.14               hd77b12b_1
graphviz                  2.50.0               hdb8b0d4_0
greenlet                  2.0.2                    pypi_0    pypi
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
gts                       0.7.6                h69fa6b1_0    conda-forge
harfbuzz                  4.3.0                hb646838_1
hijri-converter           2.3.1              pyhd8ed1ab_0    conda-forge
holidays                  0.23               pyhd8ed1ab_0    conda-forge
icc_rt                    2022.1.0             h6049295_2
icu                       58.2                 ha925a31_3
idna                      3.4              py39haa95532_0
importlib-metadata        6.0.0            py39haa95532_0
importlib_metadata        6.0.0                hd3eb1b0_0
importlib_resources       5.2.0              pyhd3eb1b0_1
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
ipykernel                 6.19.2           py39hd4e2768_0
ipython                   8.10.0           py39haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                8.0.6              pyhd8ed1ab_0    conda-forge
jedi                      0.18.1           py39haa95532_1
jinja2                    3.1.2            py39haa95532_0
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_1
jsonschema                4.17.3           py39haa95532_0
jupyter_client            8.1.0            py39haa95532_0
jupyter_core              5.3.0            py39haa95532_0
jupyter_server            1.23.4           py39haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_widgets        3.0.7              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4            py39hd77b12b_0
korean_lunar_calendar     0.3.1              pyhd8ed1ab_0    conda-forge
krb5                      1.19.4               h5b6d351_0
lerc                      3.0                  hd77b12b_0
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  14.0.6          default_hf4acfee_0
libclang13                14.0.6          default_h8992b79_0
libdeflate                1.17                 h2bbff1b_0
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                hd77b12b_6
libgd                     2.3.3                ha43c60c_1
libiconv                  1.16                 h2bbff1b_2
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.39               h8cc25b3_0
libprotobuf               3.20.3               h23ce68f_0
libsodium                 1.0.18               h62dcd97_0
libtiff                   4.5.0                h6c2663c_2
libuv                     1.44.2               h8ffe710_0    conda-forge
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.4                hbc33d0d_1
libwebp-base              1.2.4                h2bbff1b_1
libxgboost                1.7.3                hd77b12b_0
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
lightgbm                  3.3.5            py39hd77b12b_0
lightning-utilities       0.8.0              pyhd8ed1ab_0    conda-forge
llvmlite                  0.39.1           py39h23ce68f_0
lunarcalendar             0.0.9                      py_0    conda-forge
lxml                      4.9.1            py39h1985fb9_0
lz4-c                     1.9.4                h2bbff1b_0
m2-bash                   4.3.042                       5    conda-forge
m2-coreutils              8.25                        102    conda-forge
m2-filesystem             2016.04                       4    conda-forge
m2-gcc-libs               5.3.0                         4    conda-forge
m2-gmp                    6.1.0                         3    conda-forge
m2-libiconv               1.14                          3    conda-forge
m2-libintl                0.19.7                        4    conda-forge
m2-msys2-runtime          2.5.0.17080.65c939c               3    conda-forge
m2-sed                    4.2.2                         3    conda-forge
m2w64-binutils            2.25.1                        5    conda-forge
m2w64-bzip2               1.0.6                         6    conda-forge
m2w64-crt-git             5.0.0.4636.2595836               2    conda-forge
m2w64-gcc                 5.3.0                         6    conda-forge
m2w64-gcc-ada             5.3.0                         6    conda-forge
m2w64-gcc-fortran         5.3.0                         6    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gcc-objc            5.3.0                         6    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-headers-git         5.0.0.4636.c0ad18a               2    conda-forge
m2w64-isl                 0.16.1                        2    conda-forge
m2w64-libiconv            1.14                          6    conda-forge
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
m2w64-make                4.1.2351.a80a8b8               2    conda-forge
m2w64-mpc                 1.0.3                         3    conda-forge
m2w64-mpfr                3.1.4                         4    conda-forge
m2w64-pkg-config          0.29.1                        2    conda-forge
m2w64-toolchain           5.3.0                         7    conda-forge
m2w64-toolchain_win-64    2.5.0                h57928b3_0    conda-forge
m2w64-tools-git           5.0.0.4592.90b8472               2    conda-forge
m2w64-windows-default-manifest 6.4                           3    conda-forge
m2w64-winpthreads-git     5.0.0.4634.697f757               2    conda-forge
m2w64-zlib                1.2.8                        10    conda-forge
mako                      1.2.4                    pypi_0    pypi
markupsafe                2.1.1            py39h2bbff1b_0
matplotlib                3.7.1            py39haa95532_1
matplotlib-base           3.7.1            py39hf11a4ad_1
matplotlib-inline         0.1.6            py39haa95532_0
mistune                   0.8.4           py39h2bbff1b_1000
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py39h2bbff1b_0
mkl_fft                   1.3.1            py39h277e83a_0
mkl_random                1.2.2            py39hf11a4ad_0
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4                      py_0
nbclassic                 0.5.3            py39haa95532_0
nbclient                  0.5.13           py39haa95532_0
nbconvert                 6.5.4            py39haa95532_0
nbformat                  5.7.0            py39haa95532_0
nest-asyncio              1.5.6            py39haa95532_0
nfoursid                  1.0.1              pyhd8ed1ab_0    conda-forge
ninja                     1.10.2               haa95532_5
ninja-base                1.10.2               h6d14046_5
notebook                  6.5.3            py39haa95532_0
notebook-shim             0.2.2            py39haa95532_0
numba                     0.56.4           py39hf11a4ad_0
numexpr                   2.8.4            py39h5b0cc5e_0
numpy                     1.24.2                   pypi_0    pypi
numpy-base                1.23.5           py39h4da318b_0
openssl                   1.1.1t               h2bbff1b_0
optuna                    3.1.0                    pypi_0    pypi
packaging                 23.0             py39haa95532_0
pandas                    1.5.3            py39hf11a4ad_0
pandocfilters             1.5.0              pyhd3eb1b0_0
pango                     1.50.7               h78c2152_0
parso                     0.8.3              pyhd3eb1b0_0
patsy                     0.5.3            py39haa95532_0
pcre                      8.45                 hd77b12b_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.4.0            py39hd77b12b_0
pip                       23.0.1           py39haa95532_0
pixman                    0.38.0            hfa6e2cd_1003    conda-forge
platformdirs              2.5.2            py39haa95532_0
plotly                    5.14.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0                    pypi_0    pypi
ply                       3.11             py39haa95532_0
pmdarima                  2.0.3                    pypi_0    pypi
pooch                     1.4.0              pyhd3eb1b0_0
prometheus_client         0.14.1           py39haa95532_0
prompt-toolkit            3.0.36           py39haa95532_0
prophet                   1.1.2            py39he08e64f_0    conda-forge
protobuf                  3.20.3           py39hcbf5309_1    conda-forge
psutil                    5.9.0            py39h2bbff1b_0
pure_eval                 0.2.2              pyhd3eb1b0_0
py                        1.11.0                   pypi_0    pypi
py-xgboost                1.7.3            py39haa95532_0
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.11.2             pyhd3eb1b0_0
pymeeus                   0.5.12             pyhd8ed1ab_0    conda-forge
pyod                      1.0.9              pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0           py39haa95532_0
pyparsing                 3.0.9            py39haa95532_0
pyqt                      5.15.7           py39hd77b12b_0
pyqt5-sip                 12.11.0          py39hd77b12b_0
pyrsistent                0.18.0           py39h196d8e1_0
pysocks                   1.7.1            py39haa95532_0
pytest                    7.1.2                    pypi_0    pypi
pytest-cov                3.0.0                    pypi_0    pypi
pytest-forked             1.6.0                    pypi_0    pypi
pytest-xdist              2.5.0                    pypi_0    pypi
python                    3.9.16               h6244533_2
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2           py39haa95532_0
python-graphviz           0.20.1             pyh22cad53_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.12.1          cpu_py39h5e1f01c_1
pytorch-lightning         2.0.2              pyhd8ed1ab_0    conda-forge
pytz                      2023.3                   pypi_0    pypi
pywin32                   305              py39h2bbff1b_0
pywinpty                  2.0.10           py39h5da7b33_0
pyyaml                    6.0              py39hb82d6ee_4    conda-forge
pyzmq                     23.2.0           py39hd77b12b_0
qt-main                   5.15.2               he8e5bd7_8
qt-webengine              5.15.9               hb9a9bb5_5
qtwebkit                  5.212                h3ad3cdb_4
requests                  2.28.1           py39haa95532_1
scikit-learn              1.2.2            py39hd77b12b_0
scipy                     1.10.1                   pypi_0    pypi
seaborn                   0.12.2           py39haa95532_0
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                65.6.3           py39haa95532_0
shap                      0.41.0           py39h2e25243_0    conda-forge
sip                       6.6.2            py39hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
skforecast                0.8.1                    pypi_0    pypi
slicer                    0.0.7              pyhd8ed1ab_0    conda-forge
sniffio                   1.2.0            py39haa95532_1
soupsieve                 2.3.2.post1      py39haa95532_0
sqlalchemy                2.0.7                    pypi_0    pypi
sqlite                    3.41.1               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
statsforecast             1.4.0              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.5           py39h080aedc_1
tbats                     1.1.3              pyhd8ed1ab_0    conda-forge
tbb                       2021.8.0             h59b6b97_0
tenacity                  8.2.2              pyhd8ed1ab_0    conda-forge
tensorboardx              2.2                pyhd3eb1b0_0
terminado                 0.17.1           py39haa95532_0
threadpoolctl             3.1.0                    pypi_0    pypi
tinycss2                  1.2.1            py39haa95532_0
tk                        8.6.12               h2bbff1b_0
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1                    pypi_0    pypi
torchmetrics              0.11.4             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py39h2bbff1b_0
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.7.1            py39haa95532_0
typing-extensions         4.4.0            py39haa95532_0
typing_extensions         4.4.0            py39haa95532_0
tzdata                    2022g                h04d1e81_0
u8darts                   0.24.0             pyhd8ed1ab_0    conda-forge
u8darts-all               0.24.0             pyhd8ed1ab_0    conda-forge
urllib3                   1.26.15          py39haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1            py39haa95532_1
websocket-client          0.58.0           py39haa95532_4
wheel                     0.38.4           py39haa95532_0
widgetsnbextension        4.0.7              pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0            py39haa95532_0
wincertstore              0.2              py39haa95532_2
winpty                    0.4.3                         4
xarray                    2023.4.2           pyhd8ed1ab_0    conda-forge
xgboost                   1.7.5                    pypi_0    pypi
xlrd                      2.0.1              pyhd3eb1b0_0
xz                        5.2.10               h8cc25b3_1
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                hd77b12b_0
zipp                      3.11.0           py39haa95532_0
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.4                hd43e919_0

**Comment by JavierEscobarOrtiz** [comment]
Hello @harpreet-s-paul 

Could you please create a python 3.10 environment with only these dependencies and try my code again?

```bash
alembic==1.11.1
anyio==3.7.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
attrs==23.1.0
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.0.0
cffi==1.15.1
cmaes==0.9.1
colorama==0.4.6
colorlog==6.7.0
comm==0.1.3
contourpy==1.0.7
cycler==0.11.0
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
exceptiongroup==1.1.1
executing==1.2.0
fastjsonschema==2.17.1
fonttools==4.40.0
fqdn==1.5.1
greenlet==2.0.2
idna==3.4
ipykernel==6.23.2
ipython==8.14.0
ipython-genutils==0.2.0
ipywidgets==8.0.6
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
joblib==1.2.0
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyter_server==2.6.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
kiwisolver==1.4.4
lightgbm==3.3.5
Mako==1.2.4
MarkupSafe==2.1.3
matplotlib==3.7.1
matplotlib-inline==0.1.6
mistune==2.0.5
nbclassic==1.0.0
nbclient==0.8.0
nbconvert==7.5.0
nbformat==5.9.0
nest-asyncio==1.5.6
notebook==6.5.4
notebook_shim==0.2.3
numpy==1.24.3
optuna==3.2.0
overrides==7.3.1
packaging==23.1
pandas==2.0.2
pandocfilters==1.5.0
parso==0.8.3
patsy==0.5.3
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.5.3
prometheus-client==0.17.0
prompt-toolkit==3.0.38
psutil==5.9.5
pure-eval==0.2.2
pycparser==2.21
Pygments==2.15.1
pyinstrument==4.5.0
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2023.3
pywin32==306
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.1.0
qtconsole==5.4.3
QtPy==2.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
scikit-learn==1.2.2
scipy==1.10.1
seaborn==0.12.2
Send2Trash==1.8.2
session-info==1.0.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
SQLAlchemy==2.0.16
stack-data==0.6.2
statsmodels==0.14.0
stdlib-list==0.8.0
terminado==0.17.1
threadpoolctl==3.1.0
tinycss2==1.2.1
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
typing_extensions==4.6.3
tzdata==2023.3
uri-template==1.2.0
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.5.3
widgetsnbextension==4.0.7
```

**Comment by harpreet-s-paul** [comment]
I simply created a new conda venv with skforecast==0.8.1 and it worked!
