### ISSUE TITLE
Feature importance ForecasterAutoregMultiVariate - regressor LightGBM

### ISSUE THREAD

**Issue by jouet-leon** [JoaquinAmatRodrigo/skforecast#495]
Hi all, 

When I try to retrieve the important features of an AutoRegressive Multivariate model (Direct Multi Step forecasting, step=3), it works with all regressors except LightGBM. 

Indeed, for the same data, the feature importances of the model trained using XGB or Ridge regressors work (positive/negative values), but when the regressor is LightGBM, then all feature importances are equal to 0 : forecaster_trained.get_feature_importances(step=i) works but returns a dataframe with all value equal to 0 when forecaster_trained.regressor = lightgbm. 

Do you have any idea of the issue ? 

Thank's a lot for your help !

**Comment by JavierEscobarOrtiz** [comment]
Hello @jouet-leon,

What version of skforecast are you using?

Could you please run this code? I tried it on skforecast 0.8.1 and it works:

```python
# Libraries
# ==============================================================================
import pandas as pd
from lightgbm import LGBMRegressor

from skforecast.ForecasterAutoregMultiVariate import ForecasterAutoregMultiVariate

# Data download
# ==============================================================================
url = (
       'https://raw.githubusercontent.com/JoaquinAmatRodrigo/skforecast/master/'
       'data/guangyuan_air_pollution.csv'
)
data = pd.read_csv(url, sep=',')

# Data preparation
# ==============================================================================
data['date'] = pd.to_datetime(data['date'], format='%Y-%m-%d')
data = data.set_index('date')
data = data.asfreq('D')
data = data.sort_index()
data = data[['CO', 'SO2', 'PM2.5']]
data.head()
```
| date                |    CO |   SO2 |   PM2.5|
|:--------------------|------:|------:|--------:|
| 2013-03-01 00:00:00 |  9600 |   204 |     181 |
| 2013-03-02 00:00:00 | 20198 |   674 |     633 |
| 2013-03-03 00:00:00 | 47195 |  1661 |    1956 |
| 2013-03-04 00:00:00 | 15000 |   485 |     438 |
| 2013-03-05 00:00:00 | 59594 |  2001 |    3388 |

```python
# Create and fit forecaster MultiVariate
# ==============================================================================
forecaster = ForecasterAutoregMultiVariate(
                 regressor          = LGBMRegressor(random_state=123),
                 level              = 'CO',
                 lags               = 7,
                 steps              = 7,
                 transformer_series = None,
                 transformer_exog   = None,
                 weight_func        = None
             )

forecaster.fit(series=data)
forecaster.get_feature_importances(step=1)
```
|    | feature     |   importance |
|---:|:------------|-------------:|
|  0 | CO_lag_1    |          311 |
|  1 | CO_lag_2    |          198 |
|  2 | CO_lag_3    |          180 |
|  3 | CO_lag_4    |          159 |
|  4 | CO_lag_5    |          135 |
|  5 | CO_lag_6    |          164 |
|  6 | CO_lag_7    |          142 |
|  7 | SO2_lag_1   |          184 |
|  8 | SO2_lag_2   |          134 |
|  9 | SO2_lag_3   |           97 |
| 10 | SO2_lag_4   |           99 |
| 11 | SO2_lag_5   |           88 |
| 12 | SO2_lag_6   |           82 |
| 13 | SO2_lag_7   |          142 |
| 14 | PM2.5_lag_1 |          147 |
| 15 | PM2.5_lag_2 |          154 |
| 16 | PM2.5_lag_3 |          166 |
| 17 | PM2.5_lag_4 |          106 |
| 18 | PM2.5_lag_5 |          121 |
| 19 | PM2.5_lag_6 |           99 |
| 20 | PM2.5_lag_7 |           92 |

```python
import session_info
session_info.show(html=False)
```

```bash
-----
lightgbm            3.3.5
pandas              2.0.2
session_info        1.0.0
skforecast          0.9.0
-----
IPython             8.14.0
jupyter_client      8.2.0
jupyter_core        5.3.0
notebook            6.5.4
-----
Python 3.10.11 | packaged by Anaconda, Inc. | (main, May 16 2023, 00:55:32) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19044-SP0
-----
Session information updated at 2023-06-27 10:01
```
