### ISSUE TITLE
Save optimization resulst

### ISSUE THREAD

**Issue by AVPokrovsky** [JoaquinAmatRodrigo/skforecast#515]
Hi, can I save someway model training results and predict using saved data without training?
I expected last_window parameters works like this, but it seems no speed up when I used it...

**Comment by JavierEscobarOrtiz** [comment]
Hello @AVPokrovsky 

Could you please add more information about the desired behavior of last_window? 

I believe you are describing this behavior, but I do not fully understand your question:

https://skforecast.org/latest/user_guides/forecaster-in-production

**Comment by AVPokrovsky** [comment]
**I have following:**
               forecaster = ForecasterAutoreg(
                                regressor = Lasso(random_state=123,fit_intercept = param_table.loc[ind_param_table,'fit_intercept'],
                                                  alpha = param_table.loc[ind_param_table,'alpha'],
                                                  tol = param_table.loc[ind_param_table,'tol']),
                                transformer_y = DataProcessing,
                                lags = convert_lags(param_table.loc[ind_param_table,'lags'])
                             )
		forecaster.fit(y=data.loc[:,'adjclose'])
		predictions_fut = forecaster.predict(steps=Pred_steps)
**I want to train the model one time and predict without retraining. I wrote below, but no speed up**

last_window = data['adjclose'].tail(Pred_steps*2)

		forecaster.fit(y=data.loc[:,'adjclose'])
		predictions_fut = forecaster.predict(steps=Pred_steps,last_window = last_window)

               forecaster = ForecasterAutoreg(
                                regressor = Lasso(random_state=123,fit_intercept = param_table.loc[ind_param_table,'fit_intercept'],
                                                  alpha = param_table.loc[ind_param_table,'alpha'],
                                                  tol = param_table.loc[ind_param_table,'tol']),
                                transformer_y = DataProcessing,
                                lags = convert_lags(param_table.loc[ind_param_table,'lags'])
                             )
		forecaster.fit(y=data.loc[:,'adjclose'])
		predictions_fut = forecaster.predict(steps=Pred_steps)

**Comment by AVPokrovsky** [comment]
Correction - the last line of second example is
predictions_fut = forecaster.predict(steps=Pred_steps,last_window = last_window)

**Comment by JavierEscobarOrtiz** [comment]
Hi @AVPokrovsky, you are not seeing any speedup because you are fitting the forecaster twice. The goal of the `last_window` argument is to use an already fitted forecaster to do the prediction, so you don't have to fit it again, which is the main time-consuming part.

Imagine:

```python
# Train forecaster
# ==============================================================================
forecaster = ForecasterAutoreg(
                 regressor     = RandomForestRegressor(random_state=123),
                 lags          = 5,
                 forecaster_id = 'forecasting_series_y'
             )

forecaster.fit(y=data_train['y'])
```

Predict with stored last_window inside the forecaster:

```python
# Predict
# ==============================================================================
forecaster.predict(steps=3)
```
2005-02-01    0.927480
2005-03-01    0.756215
2005-04-01    0.692595

Predict with external last_window:
```python
# Predict
# ==============================================================================
last_window = new_data['y'] # len = 5 since lags = 5
forecaster.predict(steps=3, last_window=last_window)
```
2008-07-01    0.803853
2008-08-01    0.870858
2008-09-01    0.905003

The advantage is that you don't have to train the forecaster between forecasts and you are forecasting 2 different time periods.

The example makes more sense if you are loading and already trained forecaster:

https://skforecast.org/latest/user_guides/save-load-forecaster

**Comment by AVPokrovsky** [comment]
You mean I can use one fit and several calls of predict(last_window=last_window) during one program run?
I wanted to train the model ones, save it someway and use it during the next program runs

**Comment by JavierEscobarOrtiz** [comment]
Then follow this guide:

https://skforecast.org/latest/user_guides/save-load-forecaster

create forecaster -> fit forecaster -> store it

Then, you can load your forecaster and make all the predictions you want using different last windows.

**Comment by AVPokrovsky** [comment]
Ok. It works, thank you. May be it is better to combine tutorials for save-load and forecaster in production.

**Comment by JavierEscobarOrtiz** [comment]
@AVPokrovsky let us know if now is more clear 😄 

https://skforecast.org/latest/user_guides/forecaster-in-production

**Comment by AVPokrovsky** [comment]
Great! Much clearer now
