### ISSUE TITLE
Hiperparámetros

### ISSUE THREAD

**Issue by GabrielCornejo** [JoaquinAmatRodrigo/skforecast#542]
Hola Rodrigo.
Quería saber si es posible ingresar en los hiperparámetros del random forest regressor:
1) max_features
2) min_samples_leaf
3) max_samples
4) min_samples_split
Si es así, tendrás algún ejemplo?

Por otro lado, dentro de los datos que hay que poner en random_search_forecaster, qué significa "y" e "initial_train_size???

Muchas gracias.

Gabriel.

**Comment by JavierEscobarOrtiz** [comment]
Buenas @GabrielCornejo 

Te recomiendo echarle un ojo a la user guide de hyperparameter tuning, tienes muchos ejemplos de como introducir cualquier hiperparámetro:

https://skforecast.org/latest/user_guides/hyperparameter-tuning-and-lags-selection

y la de backtesting para entender la estrategia de validación que se usa para esta búsqueda:

https://skforecast.org/latest/user_guides/backtesting

La `y` hace referencia a la propia serie temporal del problema de forecasting e `initial` es el número de observaciones de esa serie que se emplean en el entrenamiento inicial antes de aplicar backtesting. Todas estas definiciones las puedes encontrar en la propia docstring de la función o la sección de API de la docu:

https://skforecast.org/latest/api/model_selection#skforecast.model_selection.model_selection.random_search_forecaster

Espero que te ayude
