### ISSUE TITLE
TimeSeriesDifferentiator No Funciona

### ISSUE THREAD

**Issue by GabrielCornejo** [JoaquinAmatRodrigo/skforecast#543]
Hola:

Me pueden decir cómo arreglar este problema?

from skforecast.preprocessing import TimeSeriesDifferentiator

ModuleNotFoundError: No module named 'skforecast.preprocessing'

Estoy usando skforecast==0.9.1

Gracias

**Comment by JoaquinAmatRodrigo** [comment]
Hola @GabrielCornejo,
TimeSeriesDifferentiator está disponible a partir de la version de skforecast 0.10.0

**Comment by GabrielCornejo** [comment]
Muchas gracias, lo acabo de arreglar.

**Comment by GabrielCornejo** [comment]
Tengo otra pregunta, ¿cómo puedo acceder a ver algunos de árboles (gráficos) de un random forest, por ejemplo, si pedí 1000 árboles, quiero ver el 35, o el 567, etc?

**Comment by JavierEscobarOrtiz** [comment]
Hola @GabrielCornejo,

Esto se sale del ámbito de skforecast y nos gustaría mantener este espacio para issues o preguntas relacionadas con el proyecto.

No obstante, nuestro amigo ChatGPT nos ha ayudado con tu pregunta:

```python
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import plot_tree

# Load data
iris = load_iris()
X, y = iris.data, iris.target

# Train random forest classifier
rf = RandomForestClassifier(n_estimators=10, random_state=42)
rf.fit(X, y)

# Plot a tree from the forest
tree_idx = 0
plt.figure(figsize=(20,10))
plot_tree(rf.estimators_[tree_idx], filled=True, 
          feature_names=iris.feature_names, class_names=list(iris.target_names))
plt.show()
```

Cambiando el `tree_idx` puedes acceder al árbol que quieras.

Espero que te ayude!

**Comment by GabrielCornejo** [comment]
Hola:

He estado tratando de "ver" alguno de los árboles generados por el Random
Forest Regressor en skforecast luego de usar hiperparámetros, pero no he
podido. Les muestro mis resultados a ver si me pueden ayudar.
Muchas gracias.

[image: image.png]

El código es muy parecido al que me enviaron, también lo obtuve de CHATGPT.
En el mensaje de error menciona que ForecasteAutorreg no tiene el atributo
'estimators_'
¿Puede que se guarde con otro nombre?

Saludos.

**Comment by JoaquinAmatRodrigo** [comment]
Hola @GabrielCornejo,
Para acceder a los atributos del regressor de un forecaster tienes que utilizar `forecaster.regressor.<attributo>`, por ejemplo `forecaster.regressor.estimators_`.

**Comment by GabrielCornejo** [comment]
Hola Joaquín.

Gracias por la aclaración. Ahora funciona.

Saludos.

Gabriel.
