### ISSUE TITLE
RandomForestRegressor predicts constant values

### ISSUE THREAD

**Issue by tavlox** [JoaquinAmatRodrigo/skforecast#548]
I am trying to fit RandomForestRegressor on the training dataset, when using the predict function to predict the values, I receive constant values through time. What is the reason for this? My goal is to forecast up to 72 hours ahead. 
Here is my code:
`from data_preparation import Preparation
from missing_timestamps import remove_duplicates
import pandas as pd
from skforecast.ForecasterAutoreg import ForecasterAutoreg
from skforecast.model_selection import grid_search_forecaster
from sklearn.ensemble import RandomForestRegressor
from skforecast.utils import save_forecaster
from skforecast.utils import load_forecaster

# marvin
data = Preparation(r'/home/ieftimska/operato-meteo-1/data/MAS_processed/ELES-MAS-5001.csv.gz', "AMBIENT_TEMPERATURE")
#data = Preparation(r'/home/iva/Desktop/operato-meteo-1/data/MAS_processed/ELES-MAS-5001.csv.gz', "AMBIENT_TEMPERATURE")
train, test = data.split()
train_processed = remove_duplicates(train)
#train_processed_ = train_processed["AMBIENT_TEMPERATURE"].copy().squeeze()
test_processed = remove_duplicates(test)
#test_processed_ = test_processed["AMBIENT_TEMPERATURE"].copy().squeeze()
whole_data = pd.concat([train_processed, test_processed])
whole_data = whole_data.rename(columns={"AMBIENT_TEMPERATURE": "y"})
whole_data.index = whole_data.index.rename("datetime")
forecaster.fit(y=whole_data.loc[:"2022", "y"])
save_forecaster(forecaster, file_name='forecaster_random_forest.py', verbose=False)
forecaster_loaded = load_forecaster('forecaster_random_forest.py', verbose=True)
predictions = forecaster_loaded.predict(steps=864)`
Here is the dataset:
[ELES-MAS-5001.csv.gz](https://github.com/JoaquinAmatRodrigo/skforecast/files/12646861/ELES-MAS-5001.csv.gz)
This is the missing_timestamps script:
`import pandas as pd
from datetime import timedelta
import numpy as np

def remove_duplicates(data):
    """
    A function that removes duplicates in timestamps and removes
    timezone information from the timestamps 
    """
    data["timestamp"] = pd.to_datetime(data["timestamp"])
    time = data["timestamp"].dt.tz_localize(None)
    data["timestamp"] = time
    data_processed = data.drop_duplicates(subset="timestamp", keep='last')
    data_processed = data_processed.set_index("timestamp")
    data_processed = data_processed.sort_index()

    return data_processed

def missing_data(data_processed):
    """
    A function that finds the dates of the missing data and fills it with the previous non-missing timestamp
    for a better visualization to present train/test data with the missing data
    """
    timestamps_series = pd.Series(data_processed.index)
    diff_5 = timedelta(hours=0, minutes=5)
    diff = timestamps_series.diff()
    more_than_5 = np.where(diff > diff_5)[0]
    previous_timestamp = more_than_5 - 1
    gaps = list()
    # a list of lists, where the first element is the previous timestamp of the missing data (succesive timestamps differ more than 5 min)
    #  and the second element is the end date of the missing data
    for i, j in zip(data_processed.iloc[previous_timestamp].index, data_processed.iloc[more_than_5].index):
        gaps.append([i, j])
    missing_timestamps = list()
    # dates of missing data where the start date is not a missing data
    for i in gaps:
        missing_timestamps.append(pd.date_range(start=i[0], end=i[1], freq='5T'))
    missing_timestamps_one_by_one = list()
    for i in missing_timestamps:
    # exclude the non-missing timestamp
        for j in i[1:]:
            missing_timestamps_one_by_one.append(j)
    values = data_processed.iloc[previous_timestamp].values
    values_list = list()
    for i, v in enumerate(values):
        values_list.append(v[0])
    # fill the missing timestamps with the values of their previous non-missing timestamps
    missing_values_filled_previous = list()
    for t, v in zip(missing_timestamps, values_list):
        missing_values_filled_previous.append([v] * len(t[1:]))
    missing_values_filled_previous_one_by_one = list()
    for i in missing_values_filled_previous:
        for j in i:
            missing_values_filled_previous_one_by_one.append(j)
    
    return missing_timestamps_one_by_one, missing_values_filled_previous_one_by_one`

**Comment by clevilll** [comment]
Hi,
I was exploring in-sample forecasting of **skforecast** package. I'm using cloud data with a frequency of 5mins (epoch=5mins). I have used `RandomForestRegressor` besides `LinearForestRegressor` from **linear-tree** package based on the recommendation of @JoaquinAmatRodrigo  in this [issue](https://github.com/skforecast/skforecast/issues/488#issuecomment-1595188283). I don't know why with my current setup performance of the RF model is saturated and turns to almost constant values and it can't capture the dynamic data. LT regressor also performed weak and I could not find its documentation to see what are the potential hyper-parameters. 

Following the full cod to reproduce the minimal example :
```python
#-----------------------------------------------------------
# Libs
#-----------------------------------------------------------
# Install linear-tree package if needed
# !pip install linear-tree
# !pip install skforecast==0.13.0
# !pip install session_info
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import *
from lineartree import LinearTreeRegressor, LinearBoostRegressor, LinearForestRegressor
from sklearn.linear_model import LinearRegression 
from sklearn.ensemble import RandomForestRegressor
from skforecast.ForecasterAutoreg import ForecasterAutoreg
print(f"Number of CPUs available: {os.cpu_count()}")

import session_info
session_info.show(html=False)


#-----------------------------------------------------------
# LOAD THE DATASET
#-----------------------------------------------------------
df = pd.read_csv('https://raw.githubusercontent.com/amcs1729/Predicting-cloud-CPU-usage-on-Azure-data/master/azure.csv')
df['timestamp'] = pd.to_datetime(df['timestamp'])
data = df.rename(columns={'min cpu': 'mincpu', 'max cpu': 'maxcpu', 'avg cpu': 'avgcpu'})

# Data preparation
# ==============================================================================

# Focus on 'timestamp' and 'avgcpu' columns
sliced_df = data[['timestamp', 'avgcpu']].copy()

# Convert data from Hz to MHz
sliced_df['avg_cpu_Mhz'] = sliced_df['avgcpu'] / 1000000

# Focus on the last 7 days (288*7 = 2016 observations)
last_week_data = sliced_df.iloc[-288*7:].reset_index(drop=True)

# Train-test split (80% train, 20% test)
train_size = int(len(last_week_data) * 0.8)
train, test = last_week_data['avg_cpu_Mhz'][:train_size], last_week_data['avg_cpu_Mhz'][train_size:]

#-----------------------------------------------------------
# Train RandomForestRegressor
#-----------------------------------------------------------
rf_forecaster = ForecasterAutoreg(
    regressor=RandomForestRegressor(random_state=42, n_jobs=-1),
    lags=288
)
rf_forecaster.fit(y=train)
rf_predictions = rf_forecaster.predict(steps=len(test))

#-----------------------------------------------------------
# Train LinearForestRegressor
#-----------------------------------------------------------

lf_forecaster = LinearForestRegressor(
    base_estimator=Ridge(random_state=42), 
    n_estimators=50, 
    n_jobs=-1,
    # Explicitly set max_features to a valid value, e.g., 'sqrt'
    max_features='sqrt'  
) 
lf_forecaster.fit(np.arange(len(train)).reshape(-1, 1), train.values)

lf_predictions = lf_forecaster.predict(np.arange(len(train), len(train) + len(test)).reshape(-1, 1))

#-----------------------------------------------------------
# Calculate Mean Squared Errors (MSE)
#-----------------------------------------------------------
rf_mse = mean_squared_error(test, rf_predictions)
lf_mse = mean_squared_error(test, lf_predictions)

print(f"Mean Squared Error (RandomForestRegressor): {rf_mse:.4f}")
print(f"Mean Squared Error (LinearForestRegressor): {lf_mse:.4f}")

#-----------------------------------------------------------
# Visualization
#-----------------------------------------------------------

# Plot predictions
plt.figure(figsize=(12, 6))

# Actual data
plt.plot(last_week_data.index[:len(train)], train, color="royalblue", label="Train Data")
plt.plot(last_week_data.index[len(train):], test,  color="navy",      label="Test Data", linestyle='dashed')

# RandomForest predictions
plt.plot(last_week_data.index[len(train):], rf_predictions, color="tomato", label="RandomForestRegressor")

# LinearTree predictions
plt.plot(last_week_data.index[len(train):], lf_predictions, color="green", label="LinearForestRegressor ")

plt.title(f'Prediction Results: RandomForestRegressor {rf_mse:.3f} vs. LinearForestRegressor {lf_mse:.3f}', fontsize=12)
plt.ylabel('CPU Usage [MHz]',   fontsize=12)
plt.xlabel('Observation Index\n Time Steps (Epochs)', fontsize=12)
plt.legend(loc='upper left')
plt.grid()
plt.tight_layout()
plt.show()
```
The following is used configurations and dependencies:
```none
Number of CPUs available: 2
-----
lineartree          NA
matplotlib          3.8.0
numpy               1.26.4
pandas              2.2.2
session_info        1.0.0
skforecast          0.13.0
sklearn             1.5.2
-----
IPython             7.34.0
jupyter_client      6.1.12
jupyter_core        5.7.2
notebook            6.5.5
-----
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
Linux-6.1.85+-x86_64-with-glibc2.35
-----
Session information updated at 2024-11-17 07:35
Mean Squared Error (RandomForestRegressor): 0.0077
Mean Squared Error (LinearForestRegressor): 0.0146
```
---
This is the output forecast results:
![image](https://github.com/user-attachments/assets/0c1323aa-fcdb-4b37-a9ab-15f94fd230ce)



Please let me know **what the best setup** for the RF model is if there is a chance to use it within `ForecasterAutoreg()` with better performance to follow the **dynamic of data** within **skforecast** package. Later I would like to extend my experiments to  [RMSF](https://skforecast.org/0.9.1/user_guides/autoregresive-forecaster#recursive-multi-step-forecasting) using another class\method: `backtesting_forecast`.

**Side note:** I'm aware of `GridSearchCV()` but it seems learning or generalization gets over\under-fitted and after a while, it returns almost constant values.
