### ISSUE TITLE
No puedo implementar Grid Search Random Forest Regressor con Diferenciación en data/h2o_exog.csv

### ISSUE THREAD

**Issue by GabrielCornejo** [JoaquinAmatRodrigo/skforecast#552]
Me aparece este error en Google Colab, estoy usando la última versión de skforecast

ValueError: Input X contains NaN.
RandomForestRegressor does not accept missing values encoded as NaN natively.

Este es mi código:

# Grid search de hiperparámetros con diferenciación interna
# ==============================================================================
steps = 12
forecaster = ForecasterAutoreg(
                regressor = RandomForestRegressor(random_state=123),
                lags      = 12,
                differentiation = 1
             )

# Hiperparámetros del regresor

param_grid = {
    'n_estimators': [2200],
    'max_depth': [10],
    'min_samples_leaf' : [2],
    'max_features' : ['sqrt'],
    'max_samples' : [0.9]
    }

resultados_grid = grid_search_forecaster(
                        forecaster         = forecaster,
                        y                  = datos_train['y'], #Train
                        param_grid         = param_grid,
                        steps              = steps,
                        refit              = True,
                        metric             = ['mean_absolute_percentage_error','mean_squared_error'],
                        initial_train_size = int(len(datos_train)*0.6),#60% Train
                        fixed_train_size   = False,
                        return_best        = True,
                        n_jobs             = 'auto',
                        verbose            = False
                  )

**Comment by JoaquinAmatRodrigo** [comment]
Hola @GabrielCornejo,
El error parece indicar que la serie `datos_train['y']` contiene datos ausentes.
Una forma de comprobarlo es: `datos_train['y'].isna().sum()`

**Comment by JoaquinAmatRodrigo** [comment]
Parece que tenemos un bug al aplicar el gridsearch, !Gracias por informarlo!
Intentaremos solucionarlo pronto.

**Comment by GabrielCornejo** [comment]
Gracias Joaquín. Parece que también afecta a uno de los gráficos finales
donde se muestran los resultados del test.

Estaré atento.

Gabriel.

**Comment by JavierEscobarOrtiz** [comment]
Buenas @GabrielCornejo, el bug debería estar solucionado. Por favor, actualiza skforecast a su versión 0.10.1 ya disponible vía `pip install skforecast`

**Comment by GabrielCornejo** [comment]
Hola:

Acabó de correr, ya no comete errores, aunque el modelo sin la tendencia es
mejor que éste. No se puede tener todo en la vida!!!

Lo aplicaré en otras series y les cuento cómo va,

Muchas gracias por la rapidez con la que arreglaron el bug.

Saludos.

Gabriel.
