### ISSUE TITLE
Usando Gaps en el pronóstico

### ISSUE THREAD

**Issue by GabrielCornejo** [JoaquinAmatRodrigo/skforecast#566]
Hola amigos:
Quiero ver la forma, y no he encontrado en el material muy bien preparado de skforecast, sobre cómo hacer un modelo de forecast que se entrene considerando un gap. Por ejemplo, El modelo considera las ventas de 5 días para predecir las ventas del séptimo, es decir hay un gap entre "y" y los rezagos del modelo, el cual empezaría en lag-2. En la única parte que he encontrado algo parecido ha sido en backtesting. ¿Me pueden decir si hay alguna parte dónde encontrar esto o bien cómo hacerlo? 
Muchas gracias

Gabriel.

**Comment by JavierEscobarOrtiz** [comment]
Buenas Gabriel,

Aquí es importante diferenciar entre las 2 estrategias de forecasting de las que disponemos, recursiva y directa.

Para la [recursiva](https://skforecast.org/latest/introduction-forecasting/introduction-forecasting#recursive-multi-step-forecasting) se debe tener en cuenta que las predicciones siempre están basadas en la anterior, es decir, para predecir el punto t+2 necesito el t+1. Por lo que el concepto de gap en realidad significa ignorar esas predicciones. En el backtesting es necesario automatizar este comportamiento con el argumento `gap`, pero a la hora de predecir, si quieres hacer una predicción digamos de 2 gap + 5 steps necesitarás llamar al método `predict` e indicar 7 steps para quedarte solo con los 5 últimos valores.

Por otro lado, en la [directa](https://skforecast.org/latest/introduction-forecasting/introduction-forecasting#direct-multi-step-forecasting) se genera un modelo para cada uno de los `steps` y, después de realizar el fit, le puedes pasar al método [predict una lista](https://skforecast.org/latest/user_guides/direct-multi-step-forecasting#prediction) para predecir solo los steps que necesitas. En el ejemplo anterior serían los steps `[3, 4, 5, 6, 7]`. De esta manera, el método `predict` solo devolverá los valores de esos steps generando un gap en las predicciones.

Espero que esto te ayude a entenderlo un poco mejor!
