### ISSUE TITLE
How to use it with planning input or other forecast as a guide?

### ISSUE THREAD

**Issue by gehal4** [JoaquinAmatRodrigo/skforecast#582]
Hi @JoaquinAmatRodrigo, 
Great package, thanks for sharing it with the community!

I was wondering how it could work with some future planned/forecasted data input as a guide? Let say we have history and then some plans for the future, is there any possibility to make the model take in consideration also the "initial plan" with a certain trust percentage (from 0 to 1)?

**Comment by JavierEscobarOrtiz** [comment]
Hi @gehal4 

I don't know if I understand your question correctly, but it seems to be a problem related to the weight that each observation has during the training process.

If this is the case, this user guide may help you:

https://skforecast.org/latest/user_guides/weighted-time-series-forecasting

Please let me know if this is what you are looking for 😄

**Comment by JoaquinAmatRodrigo** [comment]
Hi @gehal4 
When you say "initial plan", do you mean an initial estimated forecast for each of the steps in the future?

**Comment by gehal4** [comment]
Hi @JavierEscobarOrtiz, @JoaquinAmatRodrigo, 

"Initial plan" could also be the demand in retail, but also a plan of the future which is expecting a certain behavior due to the usage planned (referring as an example to a machine which might perform due to high/low usage as planned).

So as this "plan/demand" will not reflect 100% the realty due to many reasons (weather, workload changes etc.. etc.. different field different reasons), by taking into consideration both the history and this "plan/demand", how to produce a more realistic forecast ?

Hope my question is a bit clearer :)

**Comment by JoaquinAmatRodrigo** [comment]
If you can represent the 'initial plan' as a value for each step in the historical data and in the forecast horizon, then you can add it as an exogenous variable to the forecasting process. The model will learn to take it into account when generating the forecast. 

Otherwise, you would have to generate the forecast without the additional information and then combine it with the initial plan. But this combination would be external to the modelling process.

Hope this help

**Comment by gehal4** [comment]
I see your point, and I think it's a interesting idea, I'll probably try both of them separately, for the second one an average between the plan and the generated forecast, and also both at the same time to test which one is giving the best accuracy.

Thanks for your comments @JoaquinAmatRodrigo and @JavierEscobarOrtiz !
