### ISSUE TITLE
Backrest and hyper parameter tuning

### ISSUE THREAD

**Issue by yeongnamtan** [JoaquinAmatRodrigo/skforecast#610]
What is difference between the two?
How do you integrate both to improve your forecast model?

**Comment by JavierEscobarOrtiz** [comment]
Hello @yeongnamtan 

I suggest you take a look at our documentation:

- [Backtesting user guide](https://skforecast.org/latest/user_guides/backtesting)
- [Hyperparameter tuning and lags selection user guide](https://skforecast.org/latest/user_guides/hyperparameter-tuning-and-lags-selection)

Hope it helps,

Javier
