### ISSUE TITLE
Just a question about probabilistic forecasting

### ISSUE THREAD

**Issue by rexxy-sasori** [JoaquinAmatRodrigo/skforecast#612]
I know that skforecast uses bootstrapping to estimate prediction uncertainty. How is it different from regressors such as gaussian / bayesian ridge which already gives estimation uncertainty? How can I access the prediction results

**Comment by JoaquinAmatRodrigo** [comment]
Hi @rexxy-sasori,

Bootstrapping is a non-parametric method that does not assume an underlying distribution. Furthermore, it can be applied to any regression model that makes point estimate predictions (no need for probabilistic modeling). Of course, it also has some disadvantages, one of which is the computational cost. I suggest you take a look at this book for more details: https://otexts.com/fpp3/prediction-intervals.html

**Comment by rexxy-sasori** [comment]
Thanks. If I am using a probabilistic forecaster, is there even a need to do bootstrapping?

**Comment by JoaquinAmatRodrigo** [comment]
When using probabilistic models, there is no need to use bootstrapping to obtain prediction intervals. However, the current implementation of skforecast is only compatible with regressors that return a single value in its `predict` method (point estimate). Therefore, It is likely that the model you are using is not compatible with skforecast.
