### ISSUE TITLE
Issue saving ForecasterSarimax object

### ISSUE THREAD

**Issue by tyg3rr** [JoaquinAmatRodrigo/skforecast#627]
Hello! First off I just want to thank you for making this library available. It's been super helpful as I work on my masters' thesis!

I have a trained ForecasterSarimax object that I'd like to save, but I'm hitting an AttributeError

`save_forecaster(forecaster3, file_name='SARIMAX_001.py')`

with the following error traceback:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[599], [line 1](vscode-notebook-cell:?execution_count=599&line=1)
> ----> [1](vscode-notebook-cell:?execution_count=599&line=1) save_forecaster(forecaster3, file_name='SARIMAX_001.py')
> 
> File [c:\Users\ljens\scoop\apps\python\current\Lib\site-packages\skforecast\utils\utils.py:1314](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1314), in save_forecaster(forecaster, file_name, verbose)
>    [1311](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1311) joblib.dump(forecaster, filename=file_name)
>    [1313](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1313) if verbose:
> -> [1314](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1314)     forecaster.summary()
> 
> AttributeError: 'ForecasterSarimax' object has no attribute 'summary'

When I save the forecaster with `verbose=False` I don't get the error, but then I encounter the same error when loading the forecaster: 

`load_forecaster('SARIMAX_001.py')`

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[600], [line 1](vscode-notebook-cell:?execution_count=600&line=1)
> ----> [1](vscode-notebook-cell:?execution_count=600&line=1) load_forecaster('SARIMAX_001.py')
> 
> File [c:\Users\ljens\scoop\apps\python\current\Lib\site-packages\skforecast\utils\utils.py:1354](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1354), in load_forecaster(file_name, verbose)
>    [1344](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1344)     warnings.warn(
>    [1345](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1345)         (f"The skforecast version installed in the environment differs "
>    [1346](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1346)          f"from the version used to create the forecaster.\n"
>    (...)
>    [1350](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1350)          SkforecastVersionWarning
>    [1351](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1351)     )
>    [1353](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1353) if verbose:
> -> [1354](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1354)     forecaster.summary()
>    [1356](file:///C:/Users/ljens/scoop/apps/python/current/Lib/site-packages/skforecast/utils/utils.py:1356) return forecaster
> 
> AttributeError: 'ForecasterSarimax' object has no attribute 'summary'

I am having no issues saving and loading the other Forecaster objects that I created with ElasticNetCV & RandomForest. It's just SARIMAX, and I think it's related to the fact that the sarimax forecaster is wrapping the statsmodels sarimax, as opposed to the others which wrap sklearn models. 

I've had other hiccups with the SarimaxForecaster, too. I noticed another issue was opened regarding the time needed for sarimax gridsearching/backtesting - I had a similar issue as that user, with muuuch smaller data. It took over 6 hours to complete my gridsearch.

Regardless, that ^^^ is just a side note. Is there a different way to save/load Sarimax forecaster objects?

**Comment by tyg3rr** [comment]
OK I just figured out that I can load my SARIMAX forecaster if I do

`load_forecaster('SARIMAX_001.py',verbose=False)`

**Comment by JoaquinAmatRodrigo** [comment]
Hi @tyg3rr 
Thanks for using skforecast.

You are right, we missed adding the method `summary()` in the ForecasterSarimax class. Until we fix it, please use `verbose=False`.
Thanks a lot for reporting it!

**Comment by JoaquinAmatRodrigo** [comment]
Regarding the grid search for Sarimax, unfortunately, the fitting process of these models is quite slow. ForecasterSarimax is also compatible with the auto-arima process, these may be a much faster alternative, see an example here: https://cienciadedatos.net/documentos/py51-arima-sarimax-models-python#Model-tuning

Would you mind opening a new issue with this last topic? This will allow others to find it faster.

Thanks!

**Comment by JavierEscobarOrtiz** [comment]
Bug fixed in skforecast 0.12.0
