### ISSUE TITLE
grid_search_sarimax takes a very long time to run

### ISSUE THREAD

**Issue by tyg3rr** [JoaquinAmatRodrigo/skforecast#630]
Hi there!

I wanted to let you know that grid_search_sarimax takes a super long time to run. When I ran the code block below, it took ~380 minutes to complete, or just over 6 hours. Here's the code:

```python
# Grid search based on backtesting
# ==============================================================================
forecaster = ForecasterSarimax(
                regressor=Sarimax(order=(1, 1, 1), maxiter=500), # Placeholder replaced in the grid search
            )

param_grid = {
    'order': [(0, 1, 0), (0, 1, 1), (1, 1, 0), (1, 1, 1), (2, 1, 1)],
    'seasonal_order': [(0, 0, 0, 0), (0, 1, 0, 52), (1, 1, 1, 52)],
    'trend': [None, 'n', 'c']
}

results_grid = grid_search_sarimax(
                forecaster            = forecaster,
                y                     = df['cases'].loc[:end_validation],
                param_grid            = param_grid,
                steps                 = 6,
                refit                 = True,
                metric                = 'mean_absolute_error',
                initial_train_size    = len(df_train),
                fixed_train_size      = False,
                return_best           = False,
                n_jobs                = 'auto',
                suppress_warnings_fit = True,
                verbose               = False,
                show_progress         = True
            )

```

Which had the following output:

```
Number of models compared: 45.
params grid: 100%|██████████| 45/45 [7:08:10<00:00, 570.90s/it]   
```

Thankfully, I had `show_progress = True` so I could see that progress was being made and I could be patient. I'm guessing that the lengthy time required was related to my seasonal period of 52 weeks. Is there anything else I could have done to optimize this code so it would run more quickly?

**Comment by JoaquinAmatRodrigo** [comment]
Hi @tyg3rr,
Thanks for using skforecast. 
Unfortunately,  Sarimax models can become slower to fit when adding a seasonal period, especially if the seasonality is strong or the dataset is large. The auto-arima process may be a faster alternative, see an example here: https://cienciadedatos.net/documentos/py51-arima-sarimax-models-python#Model-tuning

Thanks!
