### ISSUE TITLE
add method to forecasters to return the input data that is passed to the model to make predictions

### ISSUE THREAD

**Issue by solegalli** [JoaquinAmatRodrigo/skforecast#647]
Currently, there is no way to see which data is being used to make predictions.

`create_X_y` creates the data that is used to train the model, but it;s not able to create data that is passed to "predict()`.

The data for the prediction is created in predict() but it is not exposed.

Could we capture the lines that create the input data to the regressor.predict() in a new method, say create_forecast_input() to expose that value to the user? 

It'd help with debugging and understanding what the forecaster does under the hood

**Comment by JoaquinAmatRodrigo** [comment]
I agree. I like the idea that users can explore as much as possible all the work that skforecast does internally.
I have added it to the backlog for the next release.

**Comment by JavierEscobarOrtiz** [comment]
Hello @solegalli,

The `create_predict_inputs' method will be available in skforecast `0.13.0'. 😄
