### ISSUE TITLE
XGboost using GPU

### ISSUE THREAD

**Issue by khaledbouabdallah** [JoaquinAmatRodrigo/skforecast#652]
Hello, i'm trying to run XGboost on GPU and i keep getting the warning that the input is from another device (cpu) while my XGboost is using cuda(gpu). and my runs are pretty slow and comparable if I just use cpu. I couldn't use tensors or _cudf_ with the _ForecasterAutoreg_

![image](https://github.com/JoaquinAmatRodrigo/skforecast/assets/46033722/e9650d15-c6b4-4e59-80fa-0083a283a694)

**Comment by JoaquinAmatRodrigo** [comment]
Hi, 
This issue has been inactive for a while, so we're closing it to keep the repo tidy. If needed, feel free to reopen or create a new issue.

Thanks!
