### ISSUE TITLE
Fitted Values

### ISSUE THREAD

**Issue by saumya-verma-DS** [JoaquinAmatRodrigo/skforecast#655]
After using the forecastr on train data, I want to check what my fitted values were to get rmse's. How can I check that.

**Comment by JavierEscobarOrtiz** [comment]
Hello @saumya-verma-DS 

If you are using a `ForecasterSarimax` you can check:

https://skforecast.org/latest/user_guides/forecasting-sarimax-arima#prediction-on-training-data-in-sample-predictions

For the rest of the forecasters use:

https://skforecast.org/latest/user_guides/autoregresive-forecaster#prediction-on-training-data

Hope it helps!

**Comment by saumya-verma-DS** [comment]
Actually I have used ForecasterAutoReg with Random forest regressor
