### ISSUE TITLE
Extension of the package for R

### ISSUE THREAD

**Issue by SeyyedMahdiNoori** [JoaquinAmatRodrigo/skforecast#686]
Hello, thanks for this great package.

I've used the earlier versions in my research on energy demand forecasting and had a great experience. With the R programming language becoming more widespread in the energy sector, particularly since it is becoming almost the standard programming language for energy forecasting in Australia, I was wondering if there is any plan to extend / replicate this package for R.

**Comment by JoaquinAmatRodrigo** [comment]
Hi @SeyyedMahdiNoori 
Thank you for using skforecast!

Unfortunately, we do not have enough capacity to develop and maintain the library in two different languages. For now, the only option is to use the reticulate package to interact with python from R.
