### ISSUE TITLE
Miscalculated residuals in plot_residuals()

### ISSUE THREAD

**Issue by schoulten** [JoaquinAmatRodrigo/skforecast#701]
The source code in `plot_residuals()` calculate the residuals as follows:

https://github.com/JoaquinAmatRodrigo/skforecast/blob/310915dc5b07b82acd731f43ab0f6b776ba5c6fd/skforecast/plot/plot.py#L59

But according to [Rob Hyndman's book (FPP3)](https://otexts.com/fpp3/accuracy.html#forecast-errors), the correct calculation should be:

$$e_{T+h} = y_{T+h} - \hat{y}_{T+h\|T}$$

Where $y_{T+h}$ are the "*Ground truth (correct) values*" and $\hat{y}_{T+h\|T}$ are the "*Values of predictions*"

So, the above code should change to:

```
residuals = y_true - y_pred
```

**Comment by JoaquinAmatRodrigo** [comment]
You are right, thanks for reporting!

**Comment by JoaquinAmatRodrigo** [comment]
Fixed in https://github.com/JoaquinAmatRodrigo/skforecast/pull/702
