### ISSUE TITLE
grid_search_forecaster_multiseries and ForecasterRnn

### ISSUE THREAD

**Issue by AVPokrovsky** [JoaquinAmatRodrigo/skforecast#712]
Hi, it seems grid_search_forecaster_multiseries  does not work with ForecasterRnn. Is it correct?

**Comment by JoaquinAmatRodrigo** [comment]
@FernandoCarazoMelo

**Comment by FernandoCarazoMelo** [comment]
You are right. We have not included it because the parameter optimization of a neural network is complex. It doesn't only require grid search, but also changes in the architecture. 

It should be done by calling the `create_and_compile_model` function multiple times.

**Comment by AVPokrovsky** [comment]
Ok
