### ISSUE TITLE
RNN - create_and_compile_model

### ISSUE THREAD

**Issue by AVPokrovsky** [JoaquinAmatRodrigo/skforecast#713]
Hi, when I set up create_and_compile_model parameters recurrent_units and dense_units, should I consider someway my lags and steps values?  Is there any rules or recommendations?

**Comment by FernandoCarazoMelo** [comment]
Hi @AVPokrovsky ,

The `create_and_compile_model` function creates all the logic for your RNN forecaster model.

`lags` and `steps` are independent of `recurrent_units` and `dense_units`. The general rule is that the more steps you want to predict, the more model parameters you need. Both `recurrent_units` and `dense_units` increase the number of parameters. You need to iterate by examining the model's learning curve and checking for overfitting, as shown in the documentation.

**Comment by AVPokrovsky** [comment]
Ок
