### ISSUE TITLE
Input shape of the regressor should be Input(shape=(lags, n_series))

### ISSUE THREAD

**Issue by JavierEscobarOrtiz** [JoaquinAmatRodrigo/skforecast#716]
@FernandoCarazoMelo 

I got another one with RNN regressor (below). It also appears with you code examples on RNN. It was resolved when I downgraded Tensorflow from 2.16.1 to 2.15.1 

Input shape of the regressor should be Input(shape=(lags, n_series))

_Originally posted by @AVPokrovsky in https://github.com/JoaquinAmatRodrigo/skforecast/issues/714#issuecomment-2167824884_

**Comment by AVPokrovsky** [comment]
I think it is because of keras 3.0

**Comment by FernandoCarazoMelo** [comment]
Hi @AVPokrovsky. 
You are right. 

The current version of skforecast is not compatible with keras3 (tensorflow>=2.13, <2.16). We are working to add keras3 compatibility in the next release.

**Comment by DrGreyling** [comment]
I don't know if this is still an issue, but I solved it by downgrading my python to 3.10 and installing tensorflow 2.15 first. Then I installed skforecast.

**Comment by JoaquinAmatRodrigo** [comment]
Solved in skforecast v 0.13.0
