### ISSUE TITLE
i have question about lightgbm GPU

### ISSUE THREAD

**Issue by hwoarang09** [JoaquinAmatRodrigo/skforecast#729]
i'm studying with you website,
https://cienciadedatos.net/documentos/py53-global-forecasting-models.html

there are more than 1000 buildings.

when i resample building with 

# ==============================================================================
end_train = '2016-07-31 23:59:00'
end_validation = '2016-09-30 23:59:00'
data_train = data.loc[: end_train, :].copy()
data_val   = data.loc[end_train:end_validation, :].copy()
data_test  = data.loc[end_validation:, :].copy()

#Sample 600 buildings for GPU
#==============================================================================
rng = np.random.default_rng(12345)
buildings = data['building_id'].unique()
buildings_selected = rng.choice(
                         buildings,
                         size    = 254,
                         replace = False
                     )

size less than 255
it works.

but if size over 255,
                     
error occur 
LightGBMError: bin size 257 cannot run on GPU

so i have to resample less than 255...

but i want my model learn all buildings.

Can you help me...?? Thank you!!

**Comment by JoaquinAmatRodrigo** [comment]
Hi @hwoarang09,
It seems that lightgbm only allows a maximum value of 255 bins when working with categorical features.
In skforecast >= 0.13.0 we introduced an `encoding` argument.  Could you try using encoding='ordinal'?

You can see an example here: https://skforecast.org/0.12.1/user_guides/independent-multi-time-series-forecasting#series-encoding-in-multi-series

```python
forecaster = ForecasterAutoregMultiSeries(
                   regressor = RandomForestRegressor(random_state=123),
                   lags      = 3,
                   encoding  = 'ordinal'
               )
```

**Comment by hwoarang09** [comment]
Thank you.
When i try, 
i think GPU works.

because, i can see this log.
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 8487
[LightGBM] [Info] Number of data points in the train set: 207594, number of used features: 36
[LightGBM] [Info] Using GPU Device: NVIDIA GeForce RTX 3070 Ti, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 36 dense feature groups (7.13 MB) transferred to GPU in 0.008528 secs. 0 sparse feature groups
[LightGBM] [Info] Start training from score -0.001713



but learning time is almost same with CPU

I tried
1. increase <steps> 100x in backtasting parameter
2. make long time series with copy (same value, but different index)

why learning speed is almost same with CPU?????


below, my code.
=================================================

exog_features = ['sin_day_of_week', 'cos_day_of_week', 'air_temperature', 'wind_speed']

params_lgbm = {
    'n_estimators': 500,
    'learning_rate': 0.01,
    'max_depth': 10,
    'random_state': 8520,
    #'verbose': -1,
    'device_type' : 'gpu',
    'max_bin' : 254
}
forecaster = ForecasterAutoregMultiSeries(
                 regressor          = LGBMRegressor(**params_lgbm),
                 lags               = 31, 
                 transformer_series = StandardScaler(),
                 transformer_exog   = StandardScaler(),
                 encoding  = 'ordinal',
             )



number_of_years = 10
df_list = []

for i in range(number_of_years):
    temp_df = data_pivot.copy()
    temp_df.index = temp_df.index + pd.DateOffset(years=i)
    df_list.append(temp_df)

# 데이터프레임 병합
df_expanded = pd.concat(df_list).reset_index(drop=True)
df_expanded.shape


start = datetime.now()

metric, predictions = backtesting_forecaster_multiseries(
                          forecaster         = forecaster,
                          series             = df_expanded.filter(regex='^id_'), # Select only buildings
                          exog               = df_expanded[exog_features],
                          initial_train_size = len(df_expanded.loc[:end_validation, :]),
                          steps              = 730,
                          metric             = 'mean_absolute_error',
                          #verbose            = False,
                          show_progress      = True
                      )

end = datetime.now()

mean_metric_all_buildings = metric['mean_absolute_error'].mean()
errors_all_buildings = predictions - df_expanded.loc[predictions.index, predictions.columns]
sum_abs_errors_all_buildings = errors_all_buildings.abs().sum().sum()
sum_bias_all_buildings = errors_all_buildings.sum().sum()

table_results.loc['Global model', 'mae'] = mean_metric_all_buildings
table_results.loc['Global model', 'abs_error'] = sum_abs_errors_all_buildings
table_results.loc['Global model', 'bias'] = sum_bias_all_buildings
table_results.loc['Global model', 'elapsed_time'] = end - start

print("")
print(f"Average mean absolute error for all buildings: {mean_metric_all_buildings:.0f}")
print(f"Sum of absolute errors for all buildings (x 10,000): {sum_abs_errors_all_buildings/10000:.0f}")
print(f"Bias (x 10,000): {sum_bias_all_buildings/10000:.0f}")
print(f' time : {end - start}')

**Comment by hwoarang09** [comment]
to check my GPU run, 
i run this code

`import numpy as np
import pandas as pd
import time
from lightgbm  import LGBMRegressor
from skforecast.ForecasterAutoreg import ForecasterAutoreg

# Data
# ==============================================================================
data = pd.Series(np.random.normal(size=1000000))


# Create and train forecaster with a LGBMRegressor using GPU
# ==============================================================================
forecaster = ForecasterAutoreg(
                 regressor = LGBMRegressor(n_estimators=5000, device_type='gpu'),
                 lags      = 20
             )

forecaster.fit(y=data)`

And  i open new notebook
and run this code to check GPU memory usage

`import pynvml
import time

pynvml.nvmlInit()

while True:
    handle = pynvml.nvmlDeviceGetHandleByIndex(0)  # GPU 0 사용
    info = pynvml.nvmlDeviceGetMemoryInfo(handle)
    
    print(f"Total memory: {info.total // (1024 ** 2)} MB")
    print(f"Used memory: {info.used // (1024 ** 2)} MB")
    print(f"Free memory: {info.free // (1024 ** 2)} MB")

    time.sleep(5)`

then output is here

1. before run GPU code
---------------------------------
Total memory: 8192 MB
Used memory: 944 MB
Free memory: 7247 MB
2. after run gpu code
------------------------------
Total memory: 8192 MB
Used memory: 1155 MB
Free memory: 7036 MB


but when i run backtesting code,(my second comment)
before run,  GPU usage  1300MB
after run, GPU usage go up to  1559MB
but after 

Number of observations used for initial training: 2017
Number of observations used for backtesting: 2375
    Number of folds: 4
    Number of steps per fold: 730
    Number of steps to exclude from the end of each train set before test (gap): 0
    Last fold only includes 185 observations.

Fold: 0
    Training:   0 -- 2016  (n=2017)
    Validation: 2017 -- 2746  (n=730)
Fold: 1
    Training:   0 -- 2016  (n=2017)
    Validation: 2747 -- 3476  (n=730)
Fold: 2
    Training:   0 -- 2016  (n=2017)
    Validation: 3477 -- 4206  (n=730)
Fold: 3
    Training:   0 -- 2016  (n=2017)
    Validation: 4207 -- 4391  (n=185)

C:\Users\hwoar\anaconda3\Lib\site-packages\ipywidgets\widgets\widget.py:528: DeprecationWarning:

The `ipykernel.comm.Comm` class has been deprecated. Please use the `comm` module instead.For creating comms, use the function `from comm import create_comm`.

100%
4/4 [00:00<00:00, 4.27it/s]

GPU usage go down to 1260MB

and, it take time almost same with CPU.....

in my opinion, 
gpu start to run, but due to some reason, gpu doesn work...

and my anaconda prompt

[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).

this error appear recursively..
`params_lgbm = {
    'n_estimators': 500,
    'learning_rate': 0.01,
    'max_depth': 10,
    'random_state': 8520,
    #'verbose': -1,
    'device': 'gpu',
    'gpu_platform_id': 0,
    'gpu_device_id': 0,
    'max_bin': 254,
    'num_leaves': 1024  # max_depth를 고려하여 적절한 값으로 설정

}`
so i edit parameter like this. error doesnt appear.
but when learning, GPU usage same.. go up to 1500mb and after printing 

Information of backtesting process
----------------------------------
Number of observations used for initial training: 2017
Number of observations used for backtesting: 2375
    Number of folds: 4
    Number of steps per fold: 730
    Number of steps to exclude from the end of each train set before test (gap): 0
    Last fold only includes 185 observations.

Fold: 0
    Training:   0 -- 2016  (n=2017)
    Validation: 2017 -- 2746  (n=730)
Fold: 1
    Training:   0 -- 2016  (n=2017)
    Validation: 2747 -- 3476  (n=730)
Fold: 2
    Training:   0 -- 2016  (n=2017)
    Validation: 3477 -- 4206  (n=730)
Fold: 3
    Training:   0 -- 2016  (n=2017)
    Validation: 4207 -- 4391  (n=185)

C:\Users\hwoar\anaconda3\Lib\site-packages\ipywidgets\widgets\widget.py:528: DeprecationWarning:

The `ipykernel.comm.Comm` class has been deprecated. Please use the `comm` module instead.For creating comms, use the function `from comm import create_comm`.

100%
4/4 [00:00<00:00, 4.08it/s]

down to 1200mb.
Can you help me...???
