### ISSUE TITLE
Grid search with differentiation for MultiSeries

### ISSUE THREAD

**Issue by thec0dewriter** [JoaquinAmatRodrigo/skforecast#751]
Hello,
I've been running some grid & bayesian search experiments with ForecasterAutoregMultiSeries and LightGBM.
It works fine without differentiation however when i try it with `differentiation=1` I get the following error:

> ValueError: `last_window` must have as many values as needed to generate the predictors. For this forecaster it is 6.

The error can be reproduced also by adding differentiation to:
`\tests_integration\ForecasterAuoregMultiseries\test_series_have_different_length_different_exog.ipynb`

The number in the error message depends on the lag given (It's lag+1).
Also additionally, I'm using different  exogenous values for the series (through series&exog_long_to_dict) so that might be relevant.

I've seen that in the documentation is mentioned that the differentiation for ForecasterAutoregMultiSeries is recently introduced so it needs special attention.

I've been trying to look a bit into the source code until now, but I would be curious if there are some known limitations in using differentiation with this combination?

Thank you!

**Comment by JavierEscobarOrtiz** [comment]
Hello @thec0dewriter,

Could you please confirm that you are using skforecast 0.12.1? This bug appears in skforecast 0.12.0 but has been fixed in 0.12.1.

If not, please add a reproducible example so we can look into it 😄 

Thanks a lot!

Javi

**Comment by thec0dewriter** [comment]
The issue can be reproduced on the latest fork on the repository from the  mentioned notebok  from `tests_integration` (having 0.13.0):
<img width="729" alt="image" src="https://github.com/user-attachments/assets/aba1c389-c31b-460e-861b-3c3a026960e3">

I uploaded the respective notebook file with the output and made a PR on my fork to see the diff:
https://github.com/thec0dewriter/skforecast/pull/1/files

Also on my env the package versions:
<img width="728" alt="image" src="https://github.com/user-attachments/assets/5e9a23f4-7a22-4ac3-9351-55c46bd4b551">

**Comment by JavierEscobarOrtiz** [comment]
Thanks for the input @thec0dewriter 

You are right, there is a bug in the `backtesting_forecaster_multiseries` function. It will be fixed in the next release 0.13.0, which will hopefully come in the next weeks.

If you want to fix it in your fork, all the `forecaster.window_size` in the `module_selection_multiseries` should be `forecaster.window_size_diff`

![imagen](https://github.com/user-attachments/assets/508a70d8-5c6c-4c7e-8424-87ced8781a54)

If you try it, let me know if it works. 😄 

Thanks!

**Comment by thec0dewriter** [comment]
Yes, it worked. 
Thanks a lot

**Comment by JavierEscobarOrtiz** [comment]
Hi @thec0dewriter, this issue is fixed in `skforecast 0.13.0`, which is already deployed.
