### ISSUE TITLE
Deep learning RNN - regularizers

### ISSUE THREAD

**Issue by AVPokrovsky** [JoaquinAmatRodrigo/skforecast#757]
Hi, can I set up Layer weight regularizers?

https://keras.io/2.15/api/layers/regularizers/

**Comment by JoaquinAmatRodrigo** [comment]
@FernandoCarazoMelo

**Comment by FernandoCarazoMelo** [comment]
Hey @AVPokrovsky,

Thank you for using skforecast and for your insightful comment!

Currently, the `create_and_compile` utility function does not support regularizers. The function includes the following layers: input > RNN_1 > RNN_2 > RNN_n > dense.

However, you can create any TensorFlow model and pass it to the forecasterRNN. In that model, you can use any regularizer or other RNN layers. You can easily follow the [function](https://github.com/JoaquinAmatRodrigo/skforecast/blob/master/skforecast/ForecasterRnn/utils.py) template.

Also, if you have any ideas to improve the utility function, please feel free to contribute to the library!

Let me know if you have any other questions or suggestions.

**Comment by FernandoCarazoMelo** [comment]
@JoaquinAmatRodrigo , I believe this is already answered. This is not planned to be included in the short term.
