### ISSUE TITLE
Problem related to categorical data when using `XGBRegressor`

### ISSUE THREAD

**Issue by dexterurbane** [JoaquinAmatRodrigo/skforecast#781]
Possibly a downstream issue or even a non-issue, but nonetheless this newly introduced behaviour creates an exception for v. 0.12.0 and higher that wasn't present for v. 0.11.0.

The following minimal code example crashes for skforecast v. 0.12.0 and higher:
```python
from datetime import datetime

import pandas as pd
from skforecast.ForecasterAutoregMultiSeries import ForecasterAutoregMultiSeries
from xgboost import XGBRegressor

t0 = datetime.fromisoformat('2024-01-01')
t1 = datetime.fromisoformat('2024-01-02')
idx = pd.date_range(start=t0, end=t1, freq='30min')
cols = [f'c{x}' for x in range(5)]
df = pd.DataFrame(data={c: [1.0 for _ in idx] for c in cols}, index=idx)

forecaster = ForecasterAutoregMultiSeries(regressor=XGBRegressor(), lags=range(1, 12))
forecaster.fit(series=df)
```
The error message originates from xgboost and  is the following:
```text
Traceback (most recent call last):
  File "test-skforecast/test_skforecast.py", line 15, in <module>
    forecaster.fit(series=df)
  File "/path/to/venv/lib/python3.12/site-packages/skforecast/ForecasterAutoregMultiSeries/ForecasterAutoregMultiSeries.py", line 1198, in fit

... [lines edited out for brevity]

  File "/path/to/venv/lib/python3.12/site-packages/xgboost/data.py", line 356, in _invalid_dataframe_dtype
    raise ValueError(msg)
ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:_level_skforecast: category
```

skforecast.py makes the following call at line 1198:
```python
            self.regressor.fit(X=X_train_regressor, y=y_train, **self.fit_kwargs)
```

X_train_regressor includes a categorical column `_level_skforecast`, apparently added by skforecast, and XGBRegressor's fit function complains that we haven't explicitly allowed categorical data using the `enable_categorical` keyword.

Obviously, we can fix the error message by using the following:
```python
forecaster = ForecasterAutoregMultiSeries(regressor=XGBRegressor(enable_categorical=True), lags=range(1, 12))
``` 

However, this error may well take people by surprise if they're moving from v 0.11.0 to v 0.12.0 and, in addition, it is may be confusing to people when they're using apparently non-categorical input data why this should occur. So I'm raising this as an issue just in case there's something you want to do on the skforecast end.

**Comment by JoaquinAmatRodrigo** [comment]
Hi @dexterurbane,
Thanks for bringing this up.
You are right, starting at version 0.12.0, the default encoding used by the forecaster creates a new categorical feature to encode the id of each series. Since XGBoost does not recognize categorical features by default, this causes an incompatibility.

We will probably change the default encoding to "ordinal" in the next release to avoid this problem, in the meantime there are two options.

- Specify `enable_categorical=True` as you mentioned: 

```python
forecaster = ForecasterAutoregMultiSeries(regressor=XGBRegressor(enable_categorical=True), lags=range(1, 12))
```

- Change the encoding of the regressor to ordinal or onehot.

```python
forecaster = ForecasterAutoregMultiSeries(regressor=XGBRegressor(), lags=range(1, 12), encoding='ordinal')
```

**Comment by dexterurbane** [comment]
Thanks for the information @JoaquinAmatRodrigo, sounds good!

**Comment by JavierEscobarOrtiz** [comment]
Hello @dexterurbane,

You can check the different encodings in the user guide:

https://skforecast.org/latest/user_guides/independent-multi-time-series-forecasting#series-encoding-in-multi-series

Hope it helps,

Javi
