### ISSUE TITLE
Question: how transformations are applied on global models?

### ISSUE THREAD

**Issue by mbelverf** [JoaquinAmatRodrigo/skforecast#783]
Hi all,

Could anyone says to me how the transformations are applied when dealing with global models through the 'ForecasterAutoregMultiSeries' class?

When target_transformer or exog_transformer are not null, I would like to know how the transformation is being applied internally. I was looking at the source code but to be honest, is it not 100% percent clear yet.

Is this transformation being applied individually to each id_item or the transformation is applied to all the target column considering all the id_items involved?

I'd highly apreciate more info on this topic. 

Thank you in advance. You are doing a fantastic work with this library.

**Comment by JoaquinAmatRodrigo** [comment]
Hi @mbelverf,
Thanks for using skforecast.

In `ForecasterAutoregMultiSeries` there are two options:

+ `transformer_series` is a single transformer. The transformer is internally cloned as many times as there are series, and then each one is trained using one of the series. 

+ `transformer_series` is a dictionary, you can define a different transformer for each series.

In any case, each series has it's own transformer internally. The only way to train a forecaster (and its transformers) ignoring the series id is to use `encoding= None`.

@JavierEscobarOrtiz Let's explain this better in the docs.

**Comment by mbelverf** [comment]
Thank you for your quick response Joaquin,

Then, if I understood you correctly, to each independent 'id_item' a different scaler is applied, right? That means that each transformation differs from the others.

**Comment by JoaquinAmatRodrigo** [comment]
Yes,  each series (item) has its own transformer (scaler).
You can check it by accesing `forecaster.transformer_series_`

**Comment by mbelverf** [comment]
Clear then for how to threat the targets.

And in the case of exogenous variabless. If the number of exogenous is 3 and n_items is 5. Does this mean that the number of transformers for the exogenous will be equal to 15? (3x5) I suppose that following the same idea, each exogenous column (by item) has its own transformation.

Thank you again for your help.

**Comment by JavierEscobarOrtiz** [comment]
No, for exogenous variables, the same transformer is applied to all observations under the same variable.

Imagine you have `exog_1` with a value of 10 for `series 1` and 1000 for `series 2`. The forecaster creates a column `exog_1` with values `[10. 1000]` and then transforms it using the transformer for `exog_1` in `transformer_exog`.

Here you can check the `transformer_exog` argument:

https://skforecast.org/0.13.0/user_guides/sklearn-transformers-and-pipeline#transforming-exogenous-variables

**Comment by mbelverf** [comment]
Thank you Javier.

And in terms of time-series, makes sense to use the same transformation for all the exog_1 column if we have 5 different time-series with very different values in them? 

This is something I do not have very clear, even though I have been looking in the literature for a response. I suppose it is a topic not very common.

Appreciate your help a lot.

**Comment by JoaquinAmatRodrigo** [comment]
I think this may not have a single answer that covers all scenarios. Our reasoning in skforecast is as follows:

An exogenous variable is a measure of a "phenomenon". Even though each series may have a different value, it is a value about the same "underlying phenomenon", so we transform its values taking into account all the series.

Let's consider the classic case of "predicting house prices". Among the available variables, two are "square meters of the house" and "city name".  We want to scale the variable "square meters of the house". There may be houses from different cities in the data set, but a single transformation is applied to the entire column.

**Comment by JavierEscobarOrtiz** [comment]
Well, imagine that `exog_1` represents the ambient temperature. For `series_1`, the mean will be 30; for `series_2`, it will be 40.

If you are using a `StandardScaler` from scikit-learn, using a different scaler for each series will result in both transformed means getting the value of 0. Instead, when all values are transformed together, the data will keep its natural scale.

```python
import numpy as np
from sklearn.preprocessing import StandardScaler

m = StandardScaler()
data = np.array([25, 30, 35])
data = data.reshape(-1, 1)
print(m.fit_transform(data).flatten())

m = StandardScaler()
data = np.array([37.5, 40, 42.5])
data = data.reshape(-1, 1)
print(m.fit_transform(data).flatten())

m = StandardScaler()
data = np.array([25, 30, 35, 37.5, 40, 42.5])
data = data.reshape(-1, 1)
print(m.fit_transform(data).flatten())
```

[-1.22474487  0.          1.22474487]
[-1.22474487  0.          1.22474487]
[-1.6803361  -0.84016805  0.          0.42008403  0.84016805  1.26025208]

If you don't transform all the data together, the model will understand that 30 and 40 are the same value.

**Comment by mbelverf** [comment]
It is much clear now. I have been inspecting the code and makes sense your reasoning. Now I have a better understanding about how the skforecast applies the transformations.

Thank you guys for your explanations.
