### ISSUE TITLE
Check that the index is complete when it is of type datetime and has an associated frequency

### ISSUE THREAD

**Issue by JoaquinAmatRodrigo** [JoaquinAmatRodrigo/skforecast#81]
@JavierEscobarOrtiz 
In the current implementation data index is check to verify if it is of type datetime and has frequency. It could happen  that there are missing time stamps. Should we rise a warning?

**Comment by JavierEscobarOrtiz** [comment]
@JoaquinAmatRodrigo 
It is not needed. The Pandas' method `.asfreq()` fills the gaps in the index. 
*Pandas Documentation: The values corresponding to any timesteps in the new index which were not present in the original index will be null (NaN), unless a method for filling such unknowns is provided (see the method parameter below)*

Example:

``` python
serie_1 = pd.Series(data = [1, 2, 3], index = pd.date_range(start='2022-01-01', periods=3))
serie_2 = pd.Series(data = [6, 7, 8], index = pd.date_range(start='2022-01-06', periods=3))
serie_3 = pd.concat([serie_1, serie_2])
serie_3
``` 
2022-01-01    1
2022-01-02    2
2022-01-03    3
2022-01-06    6
2022-01-07    7
2022-01-08    8
dtype: int64

``` python
serie_3 = serie_3.asfreq('1D')
serie_3
``` 
2022-01-01    1.0
2022-01-02    2.0
2022-01-03    3.0
2022-01-04    NaN
2022-01-05    NaN
2022-01-06    6.0
2022-01-07    7.0
2022-01-08    8.0
Freq: D, dtype: float64
